### ISSUE TITLE
Login page does not accept credentials used in Tuya Smart app

### ISSUE THREAD

**Issue by j0rg3n** [athombv/com.tuya#101]
### Homey version

12.0.0

### Tuya app version

1.1.1

### App diagnostics report ID

0b55a2b7-6aad-4f8a-882d-d6aefb99b9bb

### Description

Trying to login to add a device, but getting message "Tips: The account password does not match. Please re-enter the password or try to switch version"
Options are "Cancel" and "Switch region"
Region options are: International (current), and China.

If trying to create a new account, message is that that E-mail is already taken.

Have reset password two times, so fairly certain this is some random login error that is misrepresented as a password mismatch.

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
This is not an issue with the Homey app, and not something that we can solve for you. You can try using another browser (preferably using a laptop/desktop with https://my.homey.app), but the scan login could also be an option. You will be presented a QR-code which you should be able to scan in your Tuya Smart of Smart Life app on your phone.

**Comment by jorgenhs** [comment]
Thanks.
For reference, changing default browser on Android from Vivaldi to Chrome immediately resolved the issue.
