### ISSUE TITLE
Login does not work

### ISSUE THREAD

**Issue by pwvandeursen** [athombv/com.tuya#11]
When adding a device, the tuya app in my homey asks me to login. I have a tuya life account so use that one to login. Login online works, I am then asked to closed the login screen after succes. 

I end up in the homey environment, but no way to continue

![Screenshot_20240607-175209](https://github.com/athombv/com.tuya/assets/10534746/fdadfe5a-9c3f-43ed-acb9-28c91cdb3550)

Anyway to continue here?

**Comment by denniseilander** [comment]
Got the same problem. Try using the Homey web app, that worked for me since it automatically closes the window after successfully logged in.

But another issue is that when you try to add another device, it asks you to login again.

**Comment by PeterKawa** [comment]
Same. From mobile app to Chrome browser, when email/pw authenticated, the spinner continues endlessly. Killing it, and then add a new device confirms it isn´t authenticated yet, while the login process starts all over.
Mobile Firefox web app with email/pw logon: same result, and the little screen with the spinner can't be closed also. 
Had to kill Firefox....

I've also tried with the web app with Firefox @ linux authenticating with the QR code scan: it almost succeeds, but finally errors with: 
my.homey.app: `OAuth2 Client already exists`

**Comment by PeterKawa** [comment]
Workaround: 
CLI install v0.2.0 → logon → and then install v0.3.0

**Comment by denniseilander** [comment]
@PeterKawa the error `OAuth2 Client already exists` can be fixed by uninstalling the Tuya app from Homey, it seems there is already an OAuth2 client created, but it does not reset/delete if the authentication is aborted or failed.

Did you stay logged in after trying to add a device and then trying to add a different type of device? It asked me to log in again.

**Comment by PeterKawa** [comment]
> @PeterKawa the error `OAuth2 Client already exists` can be fixed by uninstalling the Tuya app from Homey, it seems there is already an OAuth2 client created, but it does not reset/delete if the authentication is aborted or failed.
> 
> Did you stay logged in after trying to add a device and then trying to add a different type of device? It asked me to log in again.

Same, @denniseilander , I had to login again
".... Closing the screen anyway, and then add a new device confirms it isn´t authenticated yet, because the login process starts all over..."

**Comment by denniseilander** [comment]
@PeterKawa ah I missed that part of your message.

Well, I'll wait till the product is a bit further developed. I thought I could add *any* Tuya device, but the most simple motion sensor is not recognized. It seems this app only fetches already existing devices from the Smart Life app, which there is already an app for that: "Tuya Cloud" or "Tuya Zigbee".

**Comment by PeterKawa** [comment]
Ah, no it's the generic driver which atm works with flowcards to *send* commands.
But I can't figure out which commands to send (see issue #11)

And, 
there's no generic driver (yet) which can *receive* commands from Tuya devices like sensors, thermostats and such; 
They can *send* values from Tuya to Homey, which you can translate as 'commands to Homey'.

I fully get while you thought it would support any device, see app store screenshot. 
It's typical for Athom: they announce/ describe/market what they want/would like, but they *don't  mention* what the actual possibilities are....
![Screenshot_20240608-142511_Chrome.jpg](https://github.com/athombv/com.tuya/assets/74005072/bc1d8ac5-0b11-493f-9df0-63aaf0670fbe)

When you look at the supported devices below that, you'll see it only supports a few devices with these very early alpha app versions.
![Screenshot_20240608-143212_Chrome.jpg](https://github.com/athombv/com.tuya/assets/74005072/809f7ace-945d-4366-b030-11829d07b4ca)


I think this app might replace the Tuya Cloud app one day, but it's now in very early test phase, not for daily use

**Comment by pwvandeursen** [comment]
De-install, install, and login through the web based version works!

It also recognizes the units installed  through the tuya gateway:

![image](https://github.com/athombv/com.tuya/assets/10534746/0ae1ed20-1c42-431b-a0bf-c8b6455a834d)

But, there is nothing we can do with them (though this might be a new issue:

![image](https://github.com/athombv/com.tuya/assets/10534746/a76fe4f6-73bc-4dd3-8f2a-2bb7b61e1639)

**Comment by denniseilander** [comment]
@PeterKawa ah, yeah the description is a bit misleading. But if I'm honest, I'm done buying the cheap "Tuya only" products, they all are made of really low quality. The only product made for Tuya, which i'm still buying is the Zigbee smart socket, which do have Watt and kWh measuring. The sensors, are just too bad to use.

The only problem is that a lot of other products are only working with the Smart Life app (not specific Tuya products), like smart bulbs, so we just need this app/integration I guess

**Comment by PeterKawa** [comment]
@pwvandeursen for the 'recognised' devices, for now, you'll need to operate them with the 'Send code' flowcards. But I haven't figured out with which code (issue #11)

**Comment by PeterKawa** [comment]
@denniseilander 
> products are only working with the Smart Life app (not specific Tuya products), like smart bulbs

Don't understand. The TuyaSmart app should fit for any Tuya device. SmartLife is just a Tuya whitelabel.

About quality: i started 4y ago with a "bag full" of Tuya wifi stuff.
It was and it is quite cheap (no Hue wallet here)
Only the sockets started to jitter after a few  years. Also I'm slowly replacing wifi with zigbee devices.

**Comment by denniseilander** [comment]
@PeterKawa I once bought the Zigbee Mini Pir motion sensor. Most of these products require a Hub, the same goes for the Aqara products, but often I can just connect them to Homey directly without any problem.

This time these sensors also requires a zigbee hub, but I only have a Homey which has zigbee built in. So I think that is the problem why I was not able to connect those sensors to Smart Life.

Just a bit out of scope, but i'm wondering why Homey is not able to detect those zigbee devices. It must have to do with either vendor lock-in from the manufacturer or it is something different.

I'm also replacing all wifi devices with Zigbee, and Matter if available.

**Comment by WeeJeWel** [comment]
Closing this issue because sign in seems to work on clean installs.
