### ISSUE TITLE
Can't connect Homey with Tuya devices using new Tuya app

### ISSUE THREAD

**Issue by iDavied** [athombv/com.tuya#111]
### Homey version

2016 Homey, versie 12.0.0

### Tuya app version

v1.1.1

### App diagnostics report ID

882F9CF9

### Description

I followed the directions on the Homey website for installing the Homey Tuya app and adding the lights from the Tuya Android app:
https://support.homey.app/hc/en-us/articles/14504423087644-Connecting-Tuya-with-Homey

However, after the last screen of the Tuya login procedure I get a message to close the screen from the Tuya website but in Homey the installation screen doesn't proceed to the next step.

Please see the screenshots for visuals:
![Screen on Homey app](https://github.com/user-attachments/assets/76dd318d-aea9-4653-8f64-393a8c7c1f14)
![Last screen on Tuya website](https://github.com/user-attachments/assets/95945f9a-58a2-4746-8cc1-48d41085fe69)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by realtallmofo** [comment]
I am also having the same issue. Have repeated the process trying other device types. Repeated message client authorised. Only option is to close the window.

**Comment by bobvandevijver** [comment]
Please try again using a laptop/desktop and https://my.homey.app: it generally works better compared to the phone app.

**Comment by iDavied** [comment]
Oddly enough, it worked!
Thanks for the tip!
