### ISSUE TITLE
Sign led light strip not dimmable

### ISSUE THREAD

**Issue by MNHPetersen** [athombv/com.tuya#112]
### Homey version

2019 Homey 12.0.0

### Tuya app version

1.1.1

### Description

Reopening #35 . It still doesn’t work. I have tried to delete and add the light strip. Brightness attribute is missing.

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
I was indeed to early closing #35, but this issue should be fixed with the next release.
