### ISSUE TITLE
[Device request]: Water Valve Controller WiFi

### ISSUE THREAD

**Issue by J33Bee** [athombv/com.tuya#113]
### Device information

Connected via Smart Life app a Water Valve controller (WiFi) version. This device I use allready for multiple years. 

https://amzn.eu/d/7MFxKvT

When I add the device to the official Tuya App in Homey it gives me no more information than attached. Please let me know if/how I can provide more info. 
![001](https://github.com/user-attachments/assets/cc1711b6-6232-44d6-8644-44675c9d3696)

### Device specification

{
  "device": {

![002](https://github.com/user-attachments/assets/a2fc9b30-38f8-4008-b73e-455bb037ce23)

**Comment by J33Bee** [comment]
From the web interface Homey I get more details... 

{ "device": { "active_time": 1652728770, "biz_type": 18, "category": "cz", "create_time": 1562158740, "icon": "smart/icon/1534303362d2e02jisz6d_0.jpg", "id": "86544400bcddc2a38696", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "SM-AW713", "name": "Sprinklers", "online": true, "owner_id": "<redacted>", "product_id": "koiGhMKwLf2ZP81g", "product_name": "Valve", "status": [ { "code": "switch", "value": false }, { "code": "countdown_1", "value": 0 } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1722584890, "uuid": "<redacted>" }, "specifications": { "category": "cz", "functions": [ { "code": "switch", "desc": "{}", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "name": "开关1倒计时", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ], "status": [ { "code": "switch", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "name": "开关1倒计时", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ] } }

**Comment by bobvandevijver** [comment]
This device identifiers itself as a socket (yes, I get the irony) and should be fully controllable if you add it using that category.

**Comment by J33Bee** [comment]
Unfortunately it doesn't. Sorry I didn't mentioned it before. Also tried to add it as a lamp, but both show the same as the "onbekend" status; not able to control/switch the device after adding.

![004](https://github.com/user-attachments/assets/902e59b8-b4e9-469d-aefb-5f17c902e990)
 
![005](https://github.com/user-attachments/assets/1ab7e56d-c9c6-4c56-80ee-f1d9f6ade8e7)

**Comment by bobvandevijver** [comment]
I see, this device is one of the "sockets" being affected by using `switch` instead of `switch_1` for their control. It doesn't really change my answer, except that you will need to wait for the 1.2.0 release (shouldn't take too long) as that should include the fix for this. You will need to add it again at that time I'm afraid.

**Comment by J33Bee** [comment]
No worries! Still working with the API key, so I will wait until 1.2.0. Thanks for all the effort! Will update here afterwards.

**Comment by J33Bee** [comment]
Working like a charm now! Thanks for your effort guys!!!
