### ISSUE TITLE
Tuya + QUOYA QL600 Smart Electric Curtain Tracks

### ISSUE THREAD

**Issue by DaveDeSmedt** [athombv/com.tuya#114]
### Homey version

Homey Pro v12

### Tuya app version

v12

### Description

I'm using Tuya in combination with different QUOYA QL600 Smart Electric Curtain Tracks. It's not a complex set-up: the curtains just go open or close, and then with a degree varying from 0-100%. Individually or together.

Was so excited after you launched the officially supported app for it. But with the best will in the world, I'd have no idea where to begin to integrate them in a flow, based on the documentation provided. How to do this?

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
This is probably a device which is not (yet) supported, so please use the correct flow to request support (and most importantly, submit the device specification).

We are also looking to create some documentation for devices that aren't supported yet (#91).
