### ISSUE TITLE
[Device request]: smoke alarm WIFIDS10WT

### ISSUE THREAD

**Issue by DanKaihoj** [athombv/com.tuya#115]
### Device information

Nedis WIFIDS10WT a smoke alarm 
 
Device spwcifications are empty in the app bit at the web they look as below. 

### Device specification

<details>

```json
  { "device": { "active_time": 1722777680, "biz_type": 0, "category": "qt", "create_time": 1598886994, "icon": "smart/icon/154886265446d512gq47i_0.png", "id": "54811034f4cfa25b8f6b", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "WIFIDS10WT", "name": "Oliver røgalarm", "online": true, "owner_id": "<redacted>", "product_id": "xwwcvhmbotekh5ye", "product_name": "Smoke Detector", "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1722777681, "uuid": "<redacted>" }, "specifications": { "category": "qt" } } 
```

</details>

**Comment by bobvandevijver** [comment]
Thank you for your request. Unfortunately it looks like that this device is an older product which is not supported by the API we use, meaning that it is not possible to support with the Homey app.

**Comment by DanKaihoj** [comment]
Ok no problem, thanks for the info, is there a place where we can see supported devices, meaning the current models so we can purchase something supported ?

Mvh

Dan Kaihøj
________________________________
Fra: Bob van de Vijver ***@***.***>
Sendt: 5. august 2024 10:02
Til: athombv/com.tuya ***@***.***>
Cc: DanKaihoj ***@***.***>; Author ***@***.***>
Emne: Re: [athombv/com.tuya] [Device request]: smoke alarm WIFIDS10WT (Issue #115)


Thank you for your request. Unfortunately it looks like that this device is an older product which is not supported by the API we use, meaning that it is not possible to support with the Homey app.

**Comment by bobvandevijver** [comment]
Unfortunately there are so many Tuya based devices that it is quite impossible to curate a list with all supported devices.

**Comment by bobvandevijver** [comment]
This might actually be related to #136, so maybe we can solve this after all in the future.

**Comment by bobvandevijver** [comment]
You can try again with the latest release: I hope it enables the use of the generic flow cards for you.
