### ISSUE TITLE
Missing dimming function

### ISSUE THREAD

**Issue by PatrikMihalik** [athombv/com.tuya#119]
### Homey version

Homey pro 2016-2019 

### Tuya app version

Version 1.1.1

### App diagnostics report ID

4437b7cc-23ed-4f7b-a9a7-1e144bb3179a

### Description

I am ussing two devices one is xiaomi bedside lamp 2,called lampa loznice. It is working correct (dimming,on-off,colorchange and so on.

Second device is led stripe gosund called led postel.
On-off works correct, but there is no possibility to change brightness, dimming bar is missing. It is possible to add it. Tru.standard tuya app is possible change brightness without problem.

Thank you.
![Screenshot_2024-08-05-22-04-33-747_app homey-edit](https://github.com/user-attachments/assets/faa83d7c-8a2f-4c29-91e3-3db4da734f4e)
![Screenshot_2024-08-05-22-04-08-520_app homey-edit](https://github.com/user-attachments/assets/4240f3dc-6036-4893-98b5-e47aa012a4d4)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Thank you for your report. We believe this will be fixed with the coming 1.2.0 release, which should hit testing this week. You will need to re-add your device at that time I'm afraid.
