### ISSUE TITLE
Tuya app

### ISSUE THREAD

**Issue by Marcc00** [athombv/com.tuya#121]
### Homey version

Homey pre 2019

### Tuya app version

1.1.1

### App diagnostics report ID

bfd10079-95c3-48df-812c-65242594e269

### Description

Always get after "authorisation..: you can close these tab

success":false,"message":"Invalid Token: undefined"}

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Please try using https://my.homey.app using a laptop/desktop and make sure that you have selected the correct country and app during authentication.

**Comment by Marcc00** [comment]
did that
after authorisation i get this
i have the smart live app

"OAuth2 Client already exists" but no added sockets...

**Comment by bobvandevijver** [comment]
Please remove the Tuya app from your Homey, restart it and try again.

**Comment by Marcc00** [comment]
Did that start homey again from scratch. Eestored backup from a while ago.
Did remove tuya app. Charge pasword. Charge password for smart live..but no

**Comment by bobvandevijver** [comment]
Great to hear your issue has been resolved: on our end we didn't change anything.
