### ISSUE TITLE
WeatherStation

### ISSUE THREAD

**Issue by Eikland** [athombv/com.tuya#122]
### Device information

https://www.aliexpress.com/item/1005007439285159.html
Tuya WiFi Intelligent Weather Clock 3-Day Weather Forecast Weather Station Wireless Thermometer Hygrometer LCD Display 3 sensors

### Device specification

<details>

```json
{
	"device": {
		"active_time": 1722195249,
		"biz_type": 18,
		"category": "qxj",
		"create_time": 1722194515,
		"icon": "smart/icon/ay1524204424146aiEgV/40021c3c75f84c5269e86f07d030208d.png",
		"id": "bf6f77489a8c3816bc8f9t",
		"ip": "<redacted>",
		"lat": "<redacted>",
		"local_key": "<redacted>",
		"lon": "<redacted>",
		"model": "",
		"name": "Værstasjon Pro™",
		"online": true,
		"owner_id": "<redacted>",
		"product_id": "nghjvn2pcjllwska",
		"product_name": "WeatherStation Pro™",
		"sub": false,
		"time_zone": "+02:00",
		"uid": "<redacted>",
		"update_time": 1722948408,
		"uuid": "<redacted>"
	},
	"specifications": {
		"category": "qxj"
	}
}
```

</details>

**Comment by bobvandevijver** [comment]
Thank you for your request. Unfortunately, based on the specification you've submitted it seems to be an undocumented device which does not expose any properties we can access, which makes it impossible to support with Homey.
