### ISSUE TITLE
Device request: Hombli Smart Socket (WiFi) with metering

### ISSUE THREAD

**Issue by Wvanoors** [athombv/com.tuya#127]
### Device information

Hombli makes lots of Tuya devices. https://www.hombli.com/nl/products/
They have an own Hombli app. 
The Hombli Smart socket works with Smart Life as well.
But it simply does not appear in Homey.
When I try to install it as an other device (Onbekend) i can log in Smart Life. After confirmation it says that OAuth2 Client already exists. 
After closing the calback page, Homey says "Log in met je account"and then stops.
I cannot open its setting and not provide further information.
Hope something can be done anyway.

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Smart sockets are already supported, so I'm closing this ticket. To make the authentication work please try https://my.homey.app using a laptop/desktop and make sure to remove and re-install the Tuya app on your Homey before doing so.

**Comment by Wvanoors** [comment]
Thanks Bob (of, aan de naam te zien, dankjewel Bob),

 

Dank voor je mail.

Ik heb ondertussen begrepen dat het zou moeten werken, maar bij werkt het toch niet.

Op de Homey Community Forum is geprobeerd me te helpen, maar zonder oplossing.

Schijnt vaker voor te komen dat aanmelden bij Tuya niet lukt. Volgens Doekse ligt dat waarschijnlijk bij Tuya.

Maar het sluiten is denk ik wel terecht, omdat de ondersteuning er officieel wel is.

 

Ik heb helaas 6 Tuya plugs liggen die dus niet aan te melden blijken en die gaan voorlopig in de la. En ik houd ook nog maar even afstand tot tuya producten.

Hopelijk komt er nog een keer een oplossing voor dit probleem.

 

Met vriendelijke groet,

Willem van Oorschot

 

Van: Bob van de Vijver ***@***.***> 
Verzonden: vrijdag 9 augustus 2024 09:49
Aan: athombv/com.tuya ***@***.***>
CC: Wvanoors ***@***.***>; Author ***@***.***>
Onderwerp: Re: [athombv/com.tuya] Device request: Hombli Smart Socket (WiFi) with metering (Issue #127)

 

Smart sockets are already supported, so I'm closing this ticket. To make the authentication work please try https://my.homey.app using a laptop/desktop and make sure to remove and re-install the Tuya app on your Homey before doing so.

**Comment by bobvandevijver** [comment]
While I am indeed Dutch, we prefer to keep using English on Github so anyone can follow what is being said here.

Authentication issues can be caused by a couple of things. You can try to change your password at Tuya: that has helped a couple of people as well. In your case I would also advise to remove the Homey Tuya app first, restart your Homey and try again using https://my.homey.app using a laptop or desktop browser with a private window, either using Firefox or Chrome (or Chromium based).
