### ISSUE TITLE
Can’t install a device (Light) on the Tuya app

### ISSUE THREAD

**Issue by ThE46x** [athombv/com.tuya#129]
### Homey version

Homey Pro early 2023 version 12.0.0

### Tuya app version

ver. 1.1.1

### App diagnostics report ID

e736c2c3-5ace-4dff-b447-6faa25ddc67f

### Description

I have all my Tuya devices in my SmartLife app.

I follow the instructions on https://support.homey.app/hc/en-us/articles/14504423087644-Connecting-Tuya-with-Homey 

And everything works find to after I click on ”Done” in the ”Confirm Authorization page”. Then it show following error: ”Permission deny (Code 1106)” in the ”New Devices Funded - Choose devices you want to add” page. 
<img width="421" alt="Skärmavbild 2024-08-08 kl  19 12 05" src="https://github.com/user-attachments/assets/81f60ac0-a9ee-4d72-a331-ce5bec27d17d">

If I start again to add a new device I get following error: ”OAuth2 Client already exist” in the ”Confirm Authorization page”. 
<img width="437" alt="Skärmavbild 2024-08-08 kl  19 06 11" src="https://github.com/user-attachments/assets/92d8257e-9e58-410d-8ae7-a602a15e1988">
When I click ”Close” (the only option) it goes back to the ”Log into your account” page and nothing more happens. 

I have deleted the Tuya app, restarted my Homey Pro and my device, re installed the Tuya app and tried to install a light or other again and the same errors happens again.

I done all above on my iPhone and my iPad and my MacBook Pro and the same shit happens on all of them. 

Please help me with this

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Closing this to clean up older tickets, but I believe it should be fixed as well. Just make sure to use https://my.homey.app for the initial pairing.

If the issue persists with the latest version you can create a new ticket.
