### ISSUE TITLE
[Device request]: Dekala Sunstone wakeup light

### ISSUE THREAD

**Issue by kaohlive** [athombv/com.tuya#133]
### Device information

This wakeuplight is in the Dekala product line one of the cheapest version. It features a main light that can be toggled and set to a dim level (that determine the sunset mode, so instead of dimming it goes from dark red to bright white).

There are other features, and listed but they dont seem to have api support I think

Those are listed in DP raw mode
led | switch_led
led_light | bright_value
time_set | -
panel_light | -
Radio | -
volume | -
Radiolist | -
clock1 | -
Delay_time | -
close_mode_set | -
sleep | -
clock2 | -
clock3 | -
clock4 | -
Internet_time | -
Radio_search | -
clock_set | -
sleep_set | -
colorLight | -
Delay

### Device specification

<details>

Wake Up Light
Product Category | dj
switch_led | Boolean | "{true,false}" 
bright_value | Integer | { "min": 1, "scale": 0, "unit": "", "max": 20, "step": 1 }
</details>

**Comment by kaohlive** [comment]
I first need some bugs to be resolved, I get and 1106 error when trying to add any type off device right now.

**Comment by bobvandevijver** [comment]
That might be solved with https://github.com/athombv/com.tuya/pull/132. This is not yet available as release, but you can try to run it locally.

**Comment by kaohlive** [comment]
{ "device": { "active_time": 1723151718, "biz_type": 0, "category": "dj", "create_time": 1547648207, "icon": "smart/icon/ay1524204424146aiEgV/1d70743480aacffbc520f4fe1a8f73a9.png", "id": "34061002cc50e3c3649a", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "ACA002", "name": "Wake Up Light <redacted>", "online": true, "owner_id": "<redacted>", "product_id": "ORL6E2BCxSYVpfs4", "product_name": "Wake Up Light", "status": [ { "code": "switch_led", "value": false }, { "code": "bright_value", "value": 12 } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1723210904, "uuid": "<redacted>" } }

**Comment by kaohlive** [comment]
So you are right, the device (at least on API level) does nto expose more than its light.
And adding that as light indeed worked.

**Comment by bobvandevijver** [comment]
Good to hear that it is indeed working as it should now! The change I linked to has been released with 1.2.1, which is currently in testing.
