### ISSUE TITLE
 V1.2.0 issue when adding a fan

### ISSUE THREAD

**Issue by GazPaz** [athombv/com.tuya#138]
### Homey version

2019 Pro v12.0.0

### Tuya app version

V1.2.0

### Description

Adding a fan returns a “specifications not found” message. There was no issue with prior version v1.1.1. Reinstalled v1.1.1 and could add fan as device again. 
![IMG_0060](https://github.com/user-attachments/assets/906f220d-f5c3-4952-9583-de15ff3e89e0)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Thank you for your report. This should be fixed with 1.2.1, which is currently in test.

**Comment by GazPaz** [comment]
Thanks. For info I have installed new version and all ok. RegardsGarySent from my iPhoneOn 12 Aug 2024, at 5:43 PM, Bob van de Vijver ***@***.***> wrote:﻿
Closed #138 as completed.
