### ISSUE TITLE
Devices not being updated

### ISSUE THREAD

**Issue by kaohlive** [athombv/com.tuya#139]
### Homey version

Homey pro 2023 12.0.

### Tuya app version

1.2.1

### App diagnostics report ID

6d5b1caf-06b3-42f5-aa03-a2283ba66ee4

### Description

My devices don't uodate state, when de device changes state due to another app, i don't get the update in homey. Also the power measurement doesn't update. Restarting the app does do a correct update to state and measurements

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by kaohlive** [comment]
Same problem with the 1.2.1 version, and i can not create diagnostic reports. It gives a rate limited error 😔

**Comment by bobvandevijver** [comment]
Are you sure you are using the test version from the store? If not, the diagnostics report won't be available.

**Comment by kaohlive** [comment]
Yes, the button is there, as it won't after a local deploy, but after giving the comment i get that error

Sent from Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by bobvandevijver** [comment]
That is interesting and should not be related to our app. Can you please try again in a few hours?

**Comment by kaohlive** [comment]
It worked this time 6d5b1caf-06b3-42f5-aa03-a2283ba66ee4

**Comment by bobvandevijver** [comment]
According to the report no webhook messages are coming, but why that is happening is unclear to me.

**Comment by kaohlive** [comment]
I have the platform.tuya.com setup. Anything i can test or try?

**Comment by kaohlive** [comment]
For one of my power sockets with power measurements it is reporting changes, I got this from the tuya developer platform:
<html>
<body>

2024-08-13 00:13:01 | Report | Power | 82.20W | device itself |  
-- | -- | -- | -- | -- | --
2024-08-13 00:10:56 | Report | Power | 52.80W | device itself |  
2024-08-13 00:10:44 | Report | Power | 84.20W | device itself |  
2024-08-13 00:10:37 | Report | Power | 89.90W | device itself |  
2024-08-13 00:08:21 | Report | Power | 72.50W | device itself |  
2024-08-13 00:07:46 | Report | Power | 105.00W | device itself |  
2024-08-13 00:07:41 | Report | Power | 63.50W | device itself |  
2024-08-13 00:06:36 | Report | Power | 87.50W | device itself |  
2024-08-13 00:06:31 | Report | Power | 59.80W | device itself |  
2024-08-13 00:04:56 | Report | Power | 84.10W | device itself


</body>
</html>

**Comment by kaohlive** [comment]
I cont find any documentation in webhooks, only a Message Service. But I can not imagine people need to enable it themselves rigth?

**Comment by kaohlive** [comment]
COuld it be that the service is suffering from the same issue as https://github.com/athombv/com.tuya/pull/132? The reason I could not add my devices before?

**Comment by bobvandevijver** [comment]
No.

**Comment by kaohlive** [comment]
See #166  that is the same problem, different accounts and devices, same missing events.

**Comment by hrabbach** [comment]
same issue here with app version 1.3.1 and a temperature & humidity sensor - no updates to readings after the initial (re)start of the app. If I can provide more information, please let me know.

**Comment by bobvandevijver** [comment]
We believe this is solved with version 1.3.3, which has just been released.

**Comment by kaohlive** [comment]
Unfortunately not, i installed that version last weekend and not a single status update for all six plugs was received.

**Comment by hrabbach** [comment]
Same problem here - one update when 1.3.3  was installed after its release, no further readings since then, even though the SmartLife app sees constant changes...
