### ISSUE TITLE
Code 501: request fail with uknown error

### ISSUE THREAD

**Issue by florisvanvredendaal** [athombv/com.tuya#145]
### Homey version

Homey Pro 2023 - v12.0.0

### Tuya app version

v1.2.1 Test

### App diagnostics report ID

10df45fb-a05a-4cd3-9ed6-3d904a83ecc9

### Description

I am trying to change a LED strip's colour, but I get a 501.
![image](https://github.com/user-attachments/assets/4ffe3eec-8cb1-4e40-8f53-5badc3980835)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
This seems to be a temporary error on the Tuya side. Please make sure your devices are reachable over internet and try again.

**Comment by florisvanvredendaal** [comment]
Unfortunately, it can't be done in my flows. The device got triggered, and the light turned on, but the colour remained the same and did not change to the colour I wanted (red):

<img width="646" alt="image" src="https://github.com/user-attachments/assets/f55a35bb-afd8-4fcc-b730-01dd6e41d392">

**Comment by bobvandevijver** [comment]
I believe that #180 fixes this issue, which will be included in the upcoming release.
