### ISSUE TITLE
[Device request]: Dovhmoh 1 PCS Tuya USB Smart Switch WiFi Controller Smart Life for USB Appliances for Alexa Home

### ISSUE THREAD

**Issue by gy1977** [athombv/com.tuya#151]
### Device information

https://www.amazon.co.uk/dp/B0CHY4SN62?psc=1&ref=ppx_yo2ov_dt_b_product_details
![41RFNlrWwhL _AC_SL1001_](https://github.com/user-attachments/assets/4013c964-2674-425a-96da-a022adfdcbda)
![Screenshot 2024-08-15 095122](https://github.com/user-attachments/assets/560e4257-c0f0-4428-be57-37b2823e2c18)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Without the device specification we cannot help you with your request, so please retrieve that. It is located in the device settings, which works best when using https://my.homey.app/.

**Comment by gy1977** [comment]
{ "device": { "active_time": 1723190862, "biz_type": 0, "category": "tdq", "create_time": 1723190862, "icon": "smart/icon/ay1521618643672lvY0O/74843c710028f981a83032b35209696f.png", "id": "bfa02f2d7b91fa905cnb80", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "", "name": "AC Infinity Cupboard Fan", "online": true, "owner_id": "<redacted>", "product_id": "cyzcfspsohhrs3v5", "product_name": "Smart Switch-1CH", "status": [ { "code": "switch_1", "value": true }, { "code": "countdown_1", "value": 0 }, { "code": "relay_status", "value": "2" }, { "code": "random_time", "value": "" }, { "code": "cycle_time", "value": "" }, { "code": "switch_inching", "value": "AAAC" }, { "code": "switch_type", "value": "button" } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1723712542, "uuid": "<redacted>" }, "specifications": { "category": "tdq", "functions": [ { "code": "switch_1", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "relay_status", "type": "Enum", "values": "{\"range\":[\"0\",\"1\",\"2\"]}" }, { "code": "random_time", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "cycle_time", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "switch_inching", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "switch_type", "type": "Enum", "values": "{\"range\":[\"flip\",\"sync\",\"button\"]}" } ], "status": [ { "code": "switch_1", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "relay_status", "type": "Enum", "values": "{\"range\":[\"0\",\"1\",\"2\"]}" }, { "code": "random_time", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "cycle_time", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "switch_inching", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "switch_type", "type": "Enum", "values": "{\"range\":[\"flip\",\"sync\",\"button\"]}" } ] } }

**Comment by gy1977** [comment]
thanks, i was adding them via the ios app but i tried using the homey web app

**Comment by bobvandevijver** [comment]
Thank you for the information. You should be able to add and control this device using the socket driver.

**Comment by gy1977** [comment]
I have tried adding this using the wall plug option, it adds with an error, see screenshots
![Screenshot 2024-08-15 132018](https://github.com/user-attachments/assets/0d095b78-6acf-4785-83a4-c50ef48c86dd)
![Screenshot 2024-08-15 132101](https://github.com/user-attachments/assets/27b65d32-2206-4dcd-b619-50bb06a65f93)

**Comment by bobvandevijver** [comment]
Right. This should be fixed with the next planned update (1.2.2).

**Comment by gy1977** [comment]
Great. Many thanks
