### ISSUE TITLE
[Device request]: Thermostat

### ISSUE THREAD

**Issue by DeWoltie** [athombv/com.tuya#164]
### Device information

I have a Magnum MRC electric floor heating thermostat added in Tuya, but this type of device is not supported in the app. Please add. Thanks

### Device specification

Update will follow

**Comment by bobvandevijver** [comment]
As the device specification is missing, we will need to close this.

**Comment by DeWoltie** [comment]
@bobvandevijver 
Sorry for the delay this is the device specification:

`{ "device": { "active_time": 1723969936, "biz_type": 0, "category": "wk", "create_time": 1611331363, "icon": "smart/icon/ay146344979723250dIO/1565770031fb8e89ed758.png", "id": "37624040500291702b64", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "", "name": "Badkamer thermostaat", "online": true, "owner_id": "<redacted>", "product_id": "ye6jdjnv5quxq3wb", "product_name": "MRC Thermostat", "status": [ { "code": "mode", "value": "hot" }, { "code": "temp_set", "value": 195 }, { "code": "temp_current", "value": 245 }, { "code": "c_f", "value": "C" } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1723969938, "uuid": "<redacted>" }, "specifications": { "category": "wk", "functions": [ { "code": "temp_set", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":41,\"max\":1040,\"scale\":1,\"step\":5}" }, { "code": "c_f", "type": "Enum", "values": "{\"range\":[\"C\",\"F\"]}" }, { "code": "mode", "type": "Enum", "values": "{\"range\":[\"hot\"]}" } ], "status": [ { "code": "temp_current", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":0,\"max\":1130,\"scale\":1,\"step\":1}" }, { "code": "temp_set", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":41,\"max\":1040,\"scale\":1,\"step\":5}" }, { "code": "c_f", "type": "Enum", "values": "{\"range\":[\"C\",\"F\"]}" }, { "code": "mode", "type": "Enum", "values": "{\"range\":[\"hot\"]}" } ] } }
`

**Comment by DeWoltie** [comment]
Maybe this is helpful 
[Homeassistant tread](https://github.com/athombv/com.tuya/issues/164#issue-2471969805)
