### ISSUE TITLE
Smoke detector, state 

### ISSUE THREAD

**Issue by andreaslundgren** [athombv/com.tuya#165]
### Homey version

Homey premium with bridge 86

### Tuya app version

1.2.3

### Description

Previously i had smart life an a scene for self testing smoke detectors, while testing a smoke detector i had a tuya siren go off, but in homey app i cant find a way to use self test for the detectors in flow, please help :)

**Comment by bobvandevijver** [comment]
Can you please submit the device requested device specification?

**Comment by bobvandevijver** [comment]
If it shows `<not available>` it just means that your device was added before we added the field to all devices. You can (temporary) add it as other/unknown device to retrieve the specification we need.

**Comment by andreaslundgren** [comment]
{ "device": { "active_time": 1722076738, "biz_type": 18, "category": "ywbj", "create_time": 1639157806, "icon": "smart/icon/bay1587648705855g44O/0fa86db1df45f550f5e2da23d90624ea.jpg", "id": "262767263c6105cd59d2", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "SNSM-SMOKEDETECTOR", "name": "brandvarnare nere", "online": true, "owner_id": "<redacted>", "product_id": "gt5nevpvnkqjlm5l", "product_name": "Smart smoke detector", "status": [ { "code": "smoke_sensor_status", "value": "normal" }, { "code": "battery_state", "value": "middle" } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1724031574, "uuid": "<redacted>" }, "specifications": { "category": "ywbj", "functions": [], "status": [ { "code": "smoke_sensor_status", "type": "Enum", "values": "{\"range\":[\"alarm\",\"normal\"]}" }, { "code": "battery_state", "type": "Enum", "values": "{\"range\":[\"low\",\"middle\",\"high\"]}" } ] }, "data_points": "<not available>" }

**Comment by bobvandevijver** [comment]
Thanks for the specification. It seems this device does not advertise a way to start the self test, so you will need to use the Tuya scene you already had. You should be able to start all your Tuya scenes using Homey flows: just don't select a device, it is located on the app level.

**Comment by andreaslundgren** [comment]
Alright, thank you!

**Comment by andreaslundgren** [comment]
Hey! I was looking in to this now but i dont think this scene thing really cover the issue.
Firstly, i cant see my newly created smart life scene in homey flow. I guess i need to sync it somehow and even if i would see it, it seems like i only can trigger a scene.

But i think i want to use the scene in the first step of the flow instead. Do you have any idea how i can achieve this?

**Comment by bobvandevijver** [comment]
When you add a scene trigger card it will autocomplete all scenes that Homey can trigger.

It is not possible to use a Tuya scene as trigger, so you are out of luck there. I believe that for your case, you can just keep the scene in Tuya.
