### ISSUE TITLE
Status devices hanging (no hiccup)

### ISSUE THREAD

**Issue by siepiee** [athombv/com.tuya#166]
### Homey version

2023 v12.0.0

### Tuya app version

V 1.2.3

### App diagnostics report ID

4c810015-a736-4f48-93c4-e4b22ab5f713

### Description

I made a ticket last week. Spoke with athom support itself and they told me to open a ticket again. My devices keep hanging 24/7. So once again it’s not a hiccup. The status of doors being open or closed is only getting updated one with a reboot. I can open doors a 100 times no status updated. So to me it seems like a software issue to me. Same with the wattage usage of sockets. Only getting a one time update again after a reboot of homey or they tuya app. You can see this in the pictures I send. So this time I hope it’s taken seriously. The socket its wattage usage is constantly changing and same with the door sensor. If I don’t touch homey it will be in the same status next year. 
![IMG_9285](https://github.com/user-attachments/assets/2c9c617c-844f-48e9-a494-f3e52d5de6a3)
![IMG_9286](https://github.com/user-attachments/assets/81e86b96-e536-4a36-841c-e0d027295a36)

**Comment by bobvandevijver** [comment]
It still does not look like an issue with the app: it just doesn't receive any updates from the Tuya cloud. New values are retrieved on app start, but that is because the data is actively retrieved at that time, instead of being pushed.

Either your devices do not generate updates on the cloud, or there might be something going on with your Tuya account. To test the latter, you will need to:

1. Remove all your Tuya devices from Homey. The easiest way is to remove the Tuya app from your Homey.
2. Create a new Tuya account (might be easiest if you switch from Smart Life to Tuya, or vice versa, so you can keep both Tuya apps on your phone)
3. Move one of your Tuya devices (a socket is your safest bet) to that new account. Make sure to remove it from the previous account first.
4. Add a new Tuya device on Homey: you should be prompted for login as you removed all existing devices.
5. See whether updates are coming in.

**Comment by siepiee** [comment]
I will try this then. Let’s see if it works. If I use the old app It does trigger but like
You said different app different way.

Met vriendelijke groet,

Sibren ter Hove
________________________________
Van: Bob van de Vijver ***@***.***>
Verzonden: Monday, August 19, 2024 2:12:12 PM
Aan: athombv/com.tuya ***@***.***>
CC: siepiee ***@***.***>; Author ***@***.***>
Onderwerp: Re: [athombv/com.tuya] Status devices hanging (no hiccup) (Issue #166)


It still does not look like an issue with the app: it just doesn't receive any updates from the Tuya cloud. New values are retrieved on app start, but that is because the data is actively retrieved at that time, instead of being pushed.

Either your devices do not generate updates on the cloud, or there might be something going on with your Tuya account. To test the latter, you will need to:

  1.  Remove all your Tuya devices from Homey. The easiest way is to remove the Tuya app from your Homey.
  2.  Create a new Tuya account (might be easiest if you switch from Smart Life to Tuya, or vice versa, so you can keep both Tuya apps on your phone)
  3.  Move one of your Tuya devices (a socket is your safest bet) to that new account. Make sure to remove it from the previous account first.
  4.  Add a new Tuya device on Homey: you should be prompted for login as you removed all existing devices.
  5.  See whether updates are coming in.

**Comment by siepiee** [comment]
Good evening,

I have tried it with a new account with Tuya. I was using smart life before this. I moved one socket.  Installed Tuya in homey again and connected it to my Tuya account instead of my smart life one. Changed the power usage constantly since my mechanical ventilation system is running on it. But it just doesn’t update. So the problem is still there. If I add the sockets with the tuya cloud app it works. And I know it's a different way of connecting but it means it is sending stuff to the cloud. I worked with Tuya cloud for almost a year now and never had issues. And 2 accounts having issues would be strange right?

kind regards ,

Sibren ter Hove
________________________________
Van: Bob van de Vijver ***@***.***>
Verzonden: maandag, augustus 19, 2024 2:12 PM
Aan: athombv/com.tuya ***@***.***>
CC: siepiee ***@***.***>; Author ***@***.***>
Onderwerp: Re: [athombv/com.tuya] Status devices hanging (no hiccup) (Issue #166)


It still does not look like an issue with the app: it just doesn't receive any updates from the Tuya cloud. New values are retrieved on app start, but that is because the data is actively retrieved at that time, instead of being pushed.

Either your devices do not generate updates on the cloud, or there might be something going on with your Tuya account. To test the latter, you will need to:

  1.  Remove all your Tuya devices from Homey. The easiest way is to remove the Tuya app from your Homey.
  2.  Create a new Tuya account (might be easiest if you switch from Smart Life to Tuya, or vice versa, so you can keep both Tuya apps on your phone)
  3.  Move one of your Tuya devices (a socket is your safest bet) to that new account. Make sure to remove it from the previous account first.
  4.  Add a new Tuya device on Homey: you should be prompted for login as you removed all existing devices.
  5.  See whether updates are coming in.

**Comment by siepiee** [comment]
I still have my old tuya cloud connected btw. Maybe that's causing it? I did remove the old devices though that I wanted to use with the new tuya app.

**Comment by bobvandevijver** [comment]
Two separate accounts having the same issues would indeed be curious, but it is also curious that you are the only one that is complaining about this issue.

Just to be sure: you only mention that the power usage isn't updated. Does the on/off state update correctly?

**Comment by siepiee** [comment]
Yes this does update correctly. But with door sensors I have issues too. They don’t get updated.

Met vriendelijke groet,

Sibren ter Hove
________________________________
Van: Bob van de Vijver ***@***.***>
Verzonden: Tuesday, August 20, 2024 12:35:49 PM
Aan: athombv/com.tuya ***@***.***>
CC: siepiee ***@***.***>; Author ***@***.***>
Onderwerp: Re: [athombv/com.tuya] Status devices hanging (no hiccup) (Issue #166)


Two separate accounts having the same issues would indeed be curious, but it is also curious that you are the only one that is complaining about this issue.

Just to be sure: you only mention that the power usage isn't updated. Does the on/off state update correctly?

**Comment by bobvandevijver** [comment]
The door sensor state could be related to #160, if they stay in the triggered state. But if the the on/off state does change correctly when changed on the socket itself or in the Tuya app, we know that the updated device information is being pushed to Homey using webhooks, but that it apparently isn't done for the power usage. That might be a device limitation, and not something we can fix. If you can submit another app diagnostics just after the on/off state has been updated by Homey (so, don't restart the app), I might be able to confirm that.

**Comment by feeloor** [comment]
I'm experiencing the same thing with both a **contact sensor** and **vibration sensor** (_which I just added a flow using the "Status shock_state gets a new String value"_). Non of them are updating or receiving updates unless I restart the app. I've tried to use both SmartLife and Tuya Smart accounts without any success.

**Comment by siepiee** [comment]
New report.

7844b4dd-9a45-49d9-a7ac-09566be2a85a

Just after the socket "slinger achtertuin" restarted.

**Comment by kaohlive** [comment]
I reported this exact problem in #139, the devices work fine get updated during any polling event (app restart for example) but dont update. Based on the log analysis it was also determined that no events from the Tuya cloud where being received.
So it is clear that not just my account or devices are impacted by this and I am no longer the only one reporting it :)

**Comment by hrabbach** [comment]
same issue here with app version 1.3.1 and a temperature & humidity sensor - no updates to readings after the initial (re)start of the app. If I can provide more information, please let me know.

**Comment by feeloor** [comment]
@bobvandevijver I tested version 1.3.3 yesterday without any success. I still don't get any updates on my vibration sensor.

**Comment by bobvandevijver** [comment]
Please open a new ticket with the information requested in the template if you still experience issues. However note that we do have support for the vibration sensor, so opening a device request for type might be a better path forward.
