### ISSUE TITLE
Wi-FI smoke detector YG400A

### ISSUE THREAD

**Issue by Jimsson1** [athombv/com.tuya#167]
### Homey version

2023 Homey Pro 12.0.1

### Tuya app version

1.2.3

### Description

Wi-FI smoke detector - YG400A
-missing battery status

**Comment by bobvandevijver** [comment]
Please use the [device request template](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) and make sure to submit the device specification.
