### ISSUE TITLE
Cannot retrieve scenes from Tuya

### ISSUE THREAD

**Issue by cyrilhendriks** [athombv/com.tuya#170]
### Homey version

2023 Homey Pro, v12.0.1

### Tuya app version

v1.2.3

### App diagnostics report ID

a489d710-962c-45df-bede-a11129afc70f

### Description

Created a tap-to-start scene in the Smartlife app:
![image](https://github.com/user-attachments/assets/e35bfa77-c883-4dc0-9380-8d8d9c02075d)

However, the Homey is not able to retrieve the scene:
![image](https://github.com/user-attachments/assets/9895eae1-295f-4fff-a1be-aed7a8b19235)

**Comment by bobvandevijver** [comment]
Thank you for your report! We have found the issue and the fix is pending: it will be included in the coming release.

**Comment by cyrilhendriks** [comment]
That is very quick, thank you!

**Comment by bobvandevijver** [comment]
It helps when the error message is very clearly visible in the log 😃
