### ISSUE TITLE
Verkeerde waarden

### ISSUE THREAD

**Issue by B1975S** [athombv/com.tuya#174]
### Homey version

Homey Pro 2023 12.0.0

### Tuya app version

com.tuya 1.2.3

### Description

https://www.gaslooswonen.nl/wifi-remote-verplaatsbaar-infraroodpaneel-350-450.html?id=277267690

En de thermostaat deze:

https://www.gaslooswonen.nl/wifi-stopcontact-thermostaat-met-losse-sensor-qh-4.html, heet in Tuya "SS501H_WIFIthermostaat"

Voor beide apparaten stuur ik de JSON-code mee die ik in Homey onder de advanced settings zag als ze als onbekend apparaat waren toegevoegd, wellicht heb je daar wat aan.
Wat betreft het issue met die 451 graden die in de Tuya app als "- -" wordt weergegeven: nu ik in Homey alle statuswijzigingen kan volgen, ben ik erachter dat bij een constante omgevingstermperatuur na een paar minuten 451 wordt doorgegeven. Zodra er een echte wijziging in temperatuur is wordt weer voor een paar minuten de juiste temperatuur doorgegeven, enzovoorts. Ik heb voor nu even een flow gemaakt met een virtual device die vanuit een Tuya event geupdated wordt en die 451 eruit filtert. En gelijk de temperatuur door 10 deelt. Dat lijkt prima te werken.
Een thermostaat is wat mij betreft hetzelfde als een heater, alleen moet je er zelf een verwarmingsapparaat aan koppelen. Implementatie in Homey zou dezelfde mogen zijn. De thermostaat heeft nog wel wat extra instellingen, maar die lijken me voor Homey niet interessant.
[IRPaneel.json](https://github.com/user-attachments/files/16675039/IRPaneel.json)
[thermostaat.json](https://github.com/user-attachments/files/16675040/thermostaat.json)

**Comment by bobvandevijver** [comment]
The scaling for the heater temperature has already been adjusted #158 (it also adds a setting so it can be manually adjusted), but that isn't released yet.

For the thermostat please open a device request.
