### ISSUE TITLE
Device.status is not iterable

### ISSUE THREAD

**Issue by Mwinte998** [athombv/com.tuya#178]
### Homey version

2023 homey pro v12.01

### Tuya app version

V1.2.3

### App diagnostics report ID

9254d9f9-c64a-4f6b-b059-8a7793f7cd9e

### Description

Recently added some matter eighttree smart plugs to Tuya and they work fine. As soon as I try and add new smart plugs to homey it finds new plugs and then says “device.status is not iterable” and only option is to close and can’t add any other plugs. If I remove the plugs from Tuya the add new devices works fine so something about the plugs is breaking it.
![IMG_2450](https://github.com/user-attachments/assets/ddf56ea5-f07f-4a3e-8548-f4895c61b248)

### Device specification

Can’t manage to add the device because or error above.

**Comment by bobvandevijver** [comment]
It looks like these devices behave differently and do not expose their status over the Tuya API, which is also why you are seeing this. However, why don't you add them directly to Homey? If you do so you do not need the Tuya cloud app, and you can control them locally using Homey.

Even if we fix this error here (and we still will), it most probably be uncontrollable using the Homey Tuya app.
