### ISSUE TITLE
can't drive unknown tuya zigbee device through advanced virtual devices

### ISSUE THREAD

**Issue by pwvandeursen** [athombv/com.tuya#18]
Got inspiration from Peter_Kawa to use a tuya device that is not yet known, through virtual devices route.

I am using a curtain zigbee device from tuya

Too be honest, not completely sure how it works but followed the steps from Peter and they resulted in an error. Was advised to create an issue here. followed these steps from peter, which led to the error below :

https://community.homey.app/t/tuya-has-officially-joined-the-talks-with-homey-program/106779/90

and this was my error after adding the virtual device I started on the flows and got the following warning, when trying to set the tuya device flow:

![image](https://github.com/athombv/com.tuya/assets/10534746/548e5b1d-247f-4249-a925-59d8cff2b1ba)

**Comment by PeterKawa** [comment]
Hi,

Unrelated to adv. virtual devices.
It's just the Tuya action card errorring.
I suggest to adjust the title of this issue to match the real problem

**Comment by bobvandevijver** [comment]
This error has been returned by the Tuya cloud API, but I am not sure as to why. Can you please try again with the latest release, and if it still fails create an app diagnostics report and share the resulting identifier here?

**Comment by bobvandevijver** [comment]
Closing this to clean up older tickets. If the issue persists with the latest version you can create a new ticket.
