### ISSUE TITLE
token is expired (Code 1010)

### ISSUE THREAD

**Issue by PeterKawa** [athombv/com.tuya#184]
### Homey version

Pro 2019 v12.0.1 (my test Homey)

### Tuya app version

v1.2.3

### App diagnostics report ID

6dd9cc4f-f7a4-4555-b337-3b8dc7a74f12

### Description

App worked fine for weeks. 
Now at every point, with every device, I get this error msg: "token is expired (Code 1010)"

![Screenshot from 2024-08-26 22-11-12](https://github.com/user-attachments/assets/c38131c6-fb35-4820-9a79-332fd8112161)

![Screenshot from 2024-08-26 22-10-50](https://github.com/user-attachments/assets/f2ddcecd-d72e-4e1c-80c6-4305a6b41f16)

**NOTE:** 
The devices still work fine with Home Assistant Tuya integration (https://www.home-assistant.io/integrations/tuya), so no issues with my wifi or internet.

What does Tuya say about this error code?
![Screenshot from 2024-08-26 22-33-43](https://github.com/user-attachments/assets/336d111d-8ae3-4d70-af95-44da1feb4b8d)

https://developer.tuya.com/en/docs/cloud/6c1636a9bd?id=Ka7kjumkoa53v

**Comment by PeterKawa** [comment]
Sidenote: on my other, daily driver Pro 2019, it works, but I had to login again to add a device.

**Comment by bobvandevijver** [comment]
Using the same Tuya account on multiple Homeys is known to be able to cause token issues in rare scenarios, for which the exact reason is currently not known. This is something we already have on the backlog, but does not have high priority.

Is it safe to assume that you did not control any Tuya device with your test Homey?

In any case you should be able to repair it using the repair procedure that each device offers: when used for a single device it should be resolved for all devices, although an app restart might be required to make the other devices available once again.
