### ISSUE TITLE
Request "Device": in-app stout & sterr Logs

### ISSUE THREAD

**Issue by PeterKawa** [athombv/com.tuya#19]
To prevent users from having to perform this procedure:
"
[To request a new device, please run the Tuya app locally using Homey CLI.
Then pair a 'Light', even if your device is not a light. Watch the logging closely for `Device: ` and copy-paste the JSON in this issue.]
"

I'd like to propose to add the `sterr` & `stout` as log info to the app, which users can enable when needed? 
It's possible, apps like tadoZones, H.A. Community, SmartThings Community provide for this functionality 

Thx!

**Comment by WeeJeWel** [comment]
I don't understand. Where would this be shown?

**Comment by PeterKawa** [comment]
Well, some apps show a log tab in the app config screen. Example of Adrian Rockall's SmartThings app:
![Screenshot_20240627-010721_Firefox.jpg](https://github.com/athombv/com.tuya/assets/74005072/a6ed0c8b-20c5-467d-a175-a2e60def1ea0)

**Comment by WeeJeWel** [comment]
Gotcha, thanks for sharing.

Because this app is Official and also published for Homey Cloud, this is not possible.

For now, we'll ask users to use Homey CLI to share their devices.
