### ISSUE TITLE
Heating device indicates temperature like 250 degrees instead 25,0 degrees

### ISSUE THREAD

**Issue by barto74** [athombv/com.tuya#195]
### Homey version

Homey Pro (Early 2023) 12.0.2

### Tuya app version

v1.2.3

### App diagnostics report ID

8758667F

### Description

I have succesfully added my Tuya heating devices to Homey, but now all temperatures (both the set temperature and the current temperature) are displayed a factor 10 higher than expected. So 25 degrees celsius would be displayed as 250 celsius. 

### Device specification

{ "device": { "active_time": 1670443850, "biz_type": 0, "category": "qn", "create_time": 1670443646, "icon": "smart/icon/ay15336238994207aJBu/a8083e78217610fb644d2b40163a6da1.png", "id": "46870533a4e57c11bb0c", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "VH8048RF-WiFi", "name": "Woonkamer", "online": true, "owner_id": "<redacted>", "product_id": "0wb7zobrnghrj0sy", "product_name": "VH Control Echo", "status": [ { "code": "switch", "value": true }, { "code": "temp_set", "value": 150 }, { "code": "temp_current", "value": 255 }, { "code": "lock", "value": false }, { "code": "work_power", "value": 0 }, { "code": "work_state", "value": "warming" } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1722372813, "uuid": "<redacted>" }, "specifications": { "category": "qn", "functions": [ { "code": "switch", "type": "Boolean", "values": "{}" }, { "code": "temp_set", "type": "Integer", "values": "{\"unit\":\"°C\",\"min\":50,\"max\":450,\"scale\":1,\"step\":5}" }, { "code": "lock", "type": "Boolean", "values": "{}" } ], "status": [ { "code": "switch", "type": "Boolean", "values": "{}" }, { "code": "temp_set", "type": "Integer", "values": "{\"unit\":\"°C\",\"min\":50,\"max\":450,\"scale\":1,\"step\":5}" }, { "code": "temp_current", "type": "Integer", "values": "{\"unit\":\"°C\",\"min\":0,\"max\":500,\"scale\":1,\"step\":5}" }, { "code": "lock", "type": "Boolean", "values": "{}" }, { "code": "work_power", "type": "Integer", "values": "{\"unit\":\"w\",\"min\":0,\"max\":5000,\"scale\":1,\"step\":1}" }, { "code": "work_state", "type": "Enum", "values": "{\"range\":[\"heating\",\"warming\"]}" } ] }, "data_points": [ { "code": "switch", "custom_name": "", "dp_id": 1, "time": 1713804018041, "type": "bool", "value": true }, { "code": "temp_set", "custom_name": "", "dp_id": 2, "time": 1725337231779, "type": "value", "value": 150 }, { "code": "temp_current", "custom_name": "", "dp_id": 3, "time": 1725343212133, "type": "value", "value": 255 }, { "code": "mode", "custom_name": "", "dp_id": 4, "time": 1713804018041, "type": "enum", "value": "manual" }, { "code": "child_lock", "custom_name": "", "dp_id": 7, "time": 1713804018041, "type": "bool", "value": false }, { "code": "work_power", "custom_name": "", "dp_id": 12, "time": 1670443850943, "type": "value", "value": 0 }, { "code": "week_program2", "custom_name": "", "dp_id": 17, "time": 1725337235439, "type": "raw", "value": "AYYF3AHgBdwEOAXcBWQF3AGGBdwB4AXcBDgF3AVkBdwBhgXcAeAF3AQ4BdwFZAXcAYYF3AHgBdwEOAXcBWQF3AGGBdwB4AXcBDgF3AVkBdwB4AXcAlgF3AQ4BdwFZAXcAeAF3AJYBdwEOAXcBWQF3A==" }, { "code": "work_state", "custom_name": "", "dp_id": 22, "time": 1721475727772, "type": "enum", "value": "warming" }, { "code": "frost_switch", "custom_name": "", "dp_id": 101, "time": 1713804018041, "type": "bool", "value": false }, { "code": "frost_temp", "custom_name": "", "dp_id": 102, "time": 1670443850943, "type": "value", "value": 30 }, { "code": "reset", "custom_name": "", "dp_id": 103, "time": 1670443850943, "type": "bool", "value": false } ] }

**Comment by bobvandevijver** [comment]
Scaling have already been added for heater devices in version 1.3.0, which should also detect the correct settings when newly adding it. You can adjust the scaling yourself in the device settings if for some reason they are not detected correctly, or when upgrading from the older app version.

**Comment by barto74** [comment]
@bobvandevijver thanks for replying so fast! I installed 1.3.0, I found the scaling settings, but they didn't have any effect. Then I deleted the devices, added them again and the scaling was recognized correctly.
So finally I can use my Tuya heating in Homey, which I am very excited about :)

**Comment by bobvandevijver** [comment]
I think the updated scaling might only be applied when new data comes in then, that would be something we need to look into then!
