### ISSUE TITLE
Login impossible

### ISSUE THREAD

**Issue by McFcologne** [athombv/com.tuya#198]
### Homey version

Homey Pro (Early 2023) 12..0.2

### Tuya app version

1.3.1

### App diagnostics report ID

a2bc50a0-29e5-4d63-96fb-bcfd0b6cc81e

### Description

The app is asking for my phone number and immediately complains about wrong password. There is no control for user nor password!
![IMG_6074](https://github.com/user-attachments/assets/4900fc09-7ac0-463d-bb36-9a4d9cc95d76)

### Device specification

it is not related to a device. Its a general issue

**Comment by McFcologne** [comment]
I found the problem. The field where I entered the phone number can also contain an email... then it works.
I think that's bad UI design. What do you expect from the user when there's a text field next to a dropdown for the country code whose alternative text starts with "phone"? Everyone enters the phone number intuitively. I was surprised because there's no phone number stored in my Tuya account and it's not intended to store one there. But I thought it was a wizard where the username comes in the next step. That made it all the more confusing when I got an error message about an incorrect password, which wasn't actually asked for anywhere.
I would suggest clearly defining the field as an email field that only accepts emails. Instead of the international area code, you could also use a simple country selection, then no one would expect the rest of the phone number to come after it.

**Comment by bobvandevijver** [comment]
This is how Tuya has designed their login experience, which is not something that we can change. We already have a clear manual that shows step by step how to get started: https://support.homey.app/hc/en-us/articles/14504423087644-Connecting-Tuya-with-Homey.
