### ISSUE TITLE
Show which sub device switches on / off in the time line. 

### ISSUE THREAD

**Issue by AdyRock** [athombv/com.tuya#2]
I have a multi gang socket strip that is added as one device and has a sub devices for each socket. When one switches on or off, the timeline just shows a Turned on or Turned off message. It would be nice to see which sub device that entry related to.

**Comment by AdyRock** [comment]
It works, but I had to delete an add the device again for the new messages to appear.

**Comment by WeeJeWel** [comment]
That's expected. Sorry, should've told you :)
