### ISSUE TITLE
Unknown device Feature missing report/message function

### ISSUE THREAD

**Issue by mruiter** [athombv/com.tuya#20]
It’s great that we have the unknown device feature . Posting commands works great . But I’m missing the picking up messages broadcasted by the device . Most devices report back like flow speed , temps , etc .
So it’s important to also have a when unknown device broadcast message you can grab it in tags with its function name and it’s value like the community tuya app . With this the unknown devices feature can do everything a device specifiek driver can . There are a lot of complex devices like heatpumps boilers flow meters airco’s fans which all have functions that are different from creator . So one can always manage to support everything thru the unknown this way

**Comment by bobvandevijver** [comment]
We are actively working on this!

**Comment by bobvandevijver** [comment]
This should become available with version 1.2.0, which should hit testing this week.

**Comment by mruiter** [comment]
The function kinda works . The auto fill of the values is missing a lot of available values.
And since i can only select the values that came back in the app and my own values that i know that get reported since they work great in the community app it's still not functioning like it should.

The Athom tuya app gives me 12 different values combined with the text bool number etc

The community app gives me 39 ! values to read from
Thats a big difference

**Comment by bobvandevijver** [comment]
@mruiter Can you please create a new ticket for that specific issue so it won't get lost?
