### ISSUE TITLE
Tuya smart scenes aren't imported into the Homey app

### ISSUE THREAD

**Issue by Herogjan** [athombv/com.tuya#200]
### Homey version

Homey app 8.4.0.1538

### Tuya app version

V1.2.3

### App diagnostics report ID

f7cc1d55-20fc-4c56-86f8-ee10e80186e9

### Description

The scenes I've created in the tuya smart app aren't visible on the tuya scenes card in homey.

I want to create a flow, which triggers a tuya scene. Now it's not possible as i get the error no scenes found.

**Comment by bobvandevijver** [comment]
This should be fixed with version 1.3.1 of the app, which is currently in testing.
