### ISSUE TITLE
Unable to select color mode on light rgb/white

### ISSUE THREAD

**Issue by Herogjan** [athombv/com.tuya#207]
### Homey version

Homey app 8.4.0.1538

### Tuya app version

V1.2.3

### App diagnostics report ID

bd9fdd6c-abcd-4754-8968-ac92b8cff7f3

### Description

I want to select the white light for the lsc floor lamp and the lsc mood light. I can only select a color from the rgb color wheel. Clicking in the middle of the color wheel white is available, however not able to select.

### Device specification
bf814f5d297046c66bf6ry
bfe0be9d128a9fb5baalpk
bfccd1f55d001d59a0eauk

**Comment by bobvandevijver** [comment]
Thank you for your report, but without the requested device specification we cannot help you. Please try to install the latest test version first (https://homey.app/a/com.tuya/test) and to re-add your lights. If the issue then persists you can create a new ticket, but do not forget to include the requested device specification.

**Comment by Herogjan** [comment]
I created a new report, now with the specifications of the three devices. I
didn't read it correctly when entering, sorry for the inconvenience.

I also tried the test version, this had the same issue.

Op ma 9 sep 2024 09:19 schreef Bob van de Vijver ***@***.***>:
