### ISSUE TITLE
Unable to select color mode on light rgb/white

### ISSUE THREAD

**Issue by Herogjan** [athombv/com.tuya#208]
### Homey version

Homey app 8.4.0.1538

### Tuya app version

V1.2.3

### App diagnostics report ID

bd9fdd6c-abcd-4754-8968-ac92b8cff7f3

### Description

I want to select the white light for the lsc floor lamp and the lsc mood light. I can only select a color from the rgb color wheel. Clicking in the middle of the color wheel white is available, however not able to select.

This is for three lights the same issue

### Device specification

LSC floor lamp links:

{ "device": { "active_time": 1724929897, "biz_type": 0, "category": "dd", "create_time": 1724929897, "icon": "smart/icon/ay1541056239985fDGjj/90fe7a4a3d1862cf811c88efba88316a.png", "id": "bfe0be9d128a9fb5baalpk", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "5325000700", "name": "LSC Floor Lamp links", "online": true, "owner_id": "<redacted>", "product_id": "k5zfxglyqrlcbp7b", "product_name": "LSC Floor Lamp", "status": [ { "code": "switch_led", "value": true }, { "code": "work_mode", "value": "white" }, { "code": "bright_value", "value": 50 }, { "code": "colour_data", "value": "{\"h\":0,\"s\":0,\"v\":1000}" }, { "code": "countdown", "value": 0 } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1725050625, "uuid": "<redacted>" }, "specifications": { "category": "dd", "functions": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown", "type": "Integer", "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "music_data", "type": "Json", "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" } ], "status": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown", "type": "Integer", "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ] }, "data_points": "<not available>" }

LSC floor lamp rechts:

{ "device": { "active_time": 1724957911, "biz_type": 0, "category": "dd", "create_time": 1724957911, "icon": "smart/icon/ay1541056239985fDGjj/90fe7a4a3d1862cf811c88efba88316a.png", "id": "bfccd1f55d001d59a0eauk", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "5325000700", "name": "LSC Floor Lamp rechts", "online": true, "owner_id": "<redacted>", "product_id": "k5zfxglyqrlcbp7b", "product_name": "LSC Floor Lamp", "status": [ { "code": "switch_led", "value": true }, { "code": "work_mode", "value": "white" }, { "code": "bright_value", "value": 50 }, { "code": "colour_data", "value": "{\"h\":0,\"s\":0,\"v\":1000}" }, { "code": "countdown", "value": 0 } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1725050629, "uuid": "<redacted>" }, "specifications": { "category": "dd", "functions": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown", "type": "Integer", "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "music_data", "type": "Json", "values": "{\"change_mode\":{\"range\":[\"direct\",\"gradient\"]}, \"bright\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"temperature\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}, \"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" } ], "status": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{\"h\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1},\"v\":{\"min\":0,\"scale\":0,\"unit\":\"\",\"max\":1000,\"step\":1}}" }, { "code": "countdown", "type": "Integer", "values": "{\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ] }, "data_points": "<not available>" }

LSC Moodlight:

{ "device": { "active_time": 1724759822, "biz_type": 0, "category": "fwd", "create_time": 1724759822, "icon": "smart/icon/ay1541056239985fDGjj/e643a2ce7eedf2cf13e90232633991d4.png", "id": "bf814f5d297046c66bf6ry", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "5325000800", "name": "LSC Moodlight", "online": true, "owner_id": "<redacted>", "product_id": "rwdljihfkp4ubn6f", "product_name": "LSC Moodlight", "status": [ { "code": "switch_led", "value": true }, { "code": "work_mode", "value": "white" }, { "code": "bright_value", "value": 50 }, { "code": "colour_data", "value": "{\"h\":60,\"s\":1000,\"v\":1000}" }, { "code": "scene_data", "value": "{\"scene_num\":203,\"scene_units\":[{\"bright\":156,\"h\":0,\"s\":0,\"temperature\":1000,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":100,\"unit_switch_duration\":100,\"v\":0},{\"bright\":0,\"h\":178,\"s\":1000,\"temperature\":0,\"unit_change_mode\":\"static\",\"unit_gradient_duration\":100,\"unit_switch_duration\":100,\"v\":1000}]}" }, { "code": "countdown", "value": 0 }, { "code": "rhythm_mode", "value": "AAAAAAA=" }, { "code": "sleep_mode", "value": "AAA=" }, { "code": "wakeup_mode", "value": "AAA=" } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1725050627, "uuid": "<redacted>" }, "specifications": { "category": "fwd", "functions": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "scene_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "music_data", "type": "Json", "values": "{}" }, { "code": "control_data", "type": "Json", "values": "{}" }, { "code": "rhythm_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "sleep_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "wakeup_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" } ], "status": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "scene_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "rhythm_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "sleep_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" }, { "code": "wakeup_mode", "type": "Raw", "values": "{\"maxlen\":\"255\"}" } ] }, "data_points": "<not available>" }

**Comment by bobvandevijver** [comment]
Thank you for the specifications. Unfortunately, according to the specification, these lights do not support temperature based control which is why the option is not shown. This can be an error on the manufacturer side if they did not correctly configure this device.

**Comment by Herogjan** [comment]
Too bad to hear. Although it's strange as in the Tuya smart app it is possible. There you can switch to white light or rgb. I'll just need to wait for the scenes import to work then.

**Comment by bobvandevijver** [comment]
That it works in the Tuya app is not strange, as that is made specifically for that exact device, where it can use non-standard interfacing to make it work. With the Homey app we only use the standard interfacing, and if that hasn't been defined correctly for a device there isn't anything we can do.

Scene control is already possible using flows cards.

**Comment by Herogjan** [comment]
I understand thanks!

Scene control isn't working yet. Scenes aren't imported. Tried yesterday
also with the test version.

Op ma 9 sep 2024 11:54 schreef Bob van de Vijver ***@***.***>:

**Comment by bobvandevijver** [comment]
Scenes are working (and greatly improved in 1.3.1): if you aren't seeing anything Tuya believes you do not have access. But this is the wrong ticket to discuss that.

**Comment by Herogjan** [comment]
Thanks for the feedback!

I've created a new bug report for the scenes issue

Op ma 9 sep 2024 12:01 schreef Bob van de Vijver ***@***.***>:
