### ISSUE TITLE
Tuya smart scenes aren't imported into the Homey app

### ISSUE THREAD

**Issue by Herogjan** [athombv/com.tuya#209]
### Homey version

Homey app 8.4.0.1538

### Tuya app version

V1.3.1

### App diagnostics report ID

0c512c7d-fe8c-43f6-bc84-ca5e6696820f

### Description

Scenes aren't imported into homey. I installed test version, still not working. Tried to re-authorize tuya, not working.

The scenes I've created in the tuya smart app aren't visible on the tuya scenes card in homey.

I want to create a flow, which triggers a tuya scene. Now it's not possible as i get the error no scenes found.

**Comment by bobvandevijver** [comment]
I believe you might be referring to scenes specifically for a particular device, but we only support scenes that are defined for your Tuya home.

**Comment by Herogjan** [comment]
Tuya home, could you elaborate? Is this a specific device or are these scenes created in the tuya my home section?

I added  a screenshot of where the scenes are created. And a screenshot of one of those scenes. And a screenshot of the devices which are used in that scene.
![Screenshot_2024-09-09-16-52-53-28_d448303990bb92d03c4d800220c6084a](https://github.com/user-attachments/assets/f6eed1ec-5e8b-4a3f-83b1-d01f73340521)

![Screenshot_2024-09-09-16-57-05-48_d448303990bb92d03c4d800220c6084a](https://github.com/user-attachments/assets/ef2389b2-0ddd-4084-a492-a51ecbd051ac)

![Screenshot_2024-09-09-16-58-49-99](https://github.com/user-attachments/assets/f59bd461-1f5c-4629-9fbd-d58a94f184e3)

**Comment by Herogjan** [comment]
Created the screen shots, waited a couple of seconds. Flow card doesn't get populated with scenes.

I want to use this flowcard in the "then" section (also only place where available).

![Screenshot_2024-09-10-17-57-20-72_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/0c251ec7-e22f-4761-9cd6-4d110a26b82f)

![Screenshot_2024-09-10-17-57-36-78_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/611bb3c2-2afd-414c-abb8-57474091a6f7)

![Screenshot_2024-09-10-17-59-55-72_4bbfc4a7dd885a2bb189f300112a7ed4](https://github.com/user-attachments/assets/de8b6140-9d4a-4fef-aa86-1fbffaab3dbe)

**Comment by julianborghuis** [comment]
I have the same

**Comment by Herogjan** [comment]
Are there any extra logs, or is the any additional information you need to
get this solved?

Op wo 11 sep 2024 09:03 schreef Bob van de Vijver ***@***.***

**Comment by bobvandevijver** [comment]
You can submit additional reports (make sure to share the report id here) so I can confirm it is the same issue.

**Comment by Herogjan** [comment]
Installed V1.3.5 tried again, still not working 

Report id:d513b067-9552-4698-a9ff-65a01556d4b4

**Comment by bobvandevijver** [comment]
The source of this issue has been found on the Tuya cloud side: they are working on a solution and hopefully this issue should fix itself somewhere next week for existing users.

It might be the case that a device repair solves the issue already, so you can try that. Otherwise you will have to wait until it is fixed on the cloud side.

**Comment by Herogjan** [comment]
That's good news!

I tried to repair the devices today (did in the past also), and now it's
working. Scenes are imported!


Op vr 20 sep 2024 13:19 schreef Bob van de Vijver ***@***.***

**Comment by bobvandevijver** [comment]
That's great to hear! 🎉
