### ISSUE TITLE
Ledstrip does not get the full (saturation) colour.

### ISSUE THREAD

**Issue by Mast1212** [athombv/com.tuya#21]
in Homey full red
![image](https://github.com/athombv/com.tuya/assets/172542736/5300b818-7e2a-4b59-b88c-b4a4454b0db9)

in Smart life
![image](https://github.com/athombv/com.tuya/assets/172542736/d1be3740-ad96-4426-98cc-7e5fb29eb905)

**Comment by bobvandevijver** [comment]
I believe this is fixed with the latest release. Can you please try, and if it doesn't, open a new ticket?
