### ISSUE TITLE
Color mode doesn't work (request fail with unknown error - Code 501)

### ISSUE THREAD

**Issue by Riddler84** [athombv/com.tuya#210]
### Homey version

Homey Pro 2023, v12.0.2

### Tuya app version

v1.2.3

### App diagnostics report ID

3503ffa3-d507-4998-964a-a8bb24f0cbaf

### Description

In one of my lamps, I can't switch to color mode in Homey. When I try, I get the error message "request fail with unknown error (Code 501)."

The UI for this lamp looks different in the original Tuya app compared to my other lamps. Instead of switching between white and color modes, I can turn both modes on and off independently and also adjust colors or white tones for each. However, only when I turn off the white light does the color mode activate for the lamp.

But if I only activate the color mode in the Tuya app, the display in Homey also switches to color mode. However, when I try to change the color, the same error message appears as before. Additionally, I can't switch back to white light in Homey either. In that case, the error "param is empty (Code 1100)" appears.

At that point, brightness can no longer be adjusted either, as the Code 501 error occurs again. At this stage, I can effectively only turn the lamp on and off in Homey.

### Device specification

{ "device": { "active_time": 1667128527, "biz_type": 0, "category": "xdd", "create_time": 1667128527, "icon": "smart/icon/ay1529600514580n5dKQ/f9664f680be14a81cdfcafa778351865.png", "id": "bfb3939b4d8fd0aa95xs12", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "", "name": "Hisco RGBCW ALL WIFI/BLE+I...", "online": true, "owner_id": "<redacted>", "product_id": "jrgvsltz3pskbbpj", "product_name": "Hisco RGBCW ALL WIFI/BLE+IR10 CB3S", "status": [ { "code": "switch_led", "value": true }, { "code": "work_mode", "value": "white" }, { "code": "bright_value", "value": 208 }, { "code": "temp_value", "value": 120 }, { "code": "colour_data", "value": "{\"h\":357,\"s\":820,\"v\":1000}" }, { "code": "countdown", "value": 0 }, { "code": "do_not_disturb", "value": false } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1725715142, "uuid": "<redacted>" }, "specifications": { "category": "xdd", "functions": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "temp_value", "type": "Integer", "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "music_data", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "control_data", "type": "String", "values": "{\"maxlen\":255}" }, { "code": "do_not_disturb", "type": "Boolean", "values": "{}" } ], "status": [ { "code": "switch_led", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"music\"]}" }, { "code": "bright_value", "type": "Integer", "values": "{\"min\":10,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "temp_value", "type": "Integer", "values": "{\"min\":0,\"max\":1000,\"scale\":0,\"step\":1}" }, { "code": "colour_data", "type": "Json", "values": "{}" }, { "code": "countdown", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "do_not_disturb", "type": "Boolean", "values": "{}" } ] }, "data_points": [ { "code": "switch_led", "custom_name": "", "dp_id": 20, "time": 1725901545111, "type": "bool", "value": true }, { "code": "work_mode", "custom_name": "", "dp_id": 21, "time": 1725188379606, "type": "enum", "value": "white" }, { "code": "bright_value", "custom_name": "", "dp_id": 22, "time": 1725901545218, "type": "value", "value": 208 }, { "code": "temp_value", "custom_name": "", "dp_id": 23, "time": 1725901545218, "type": "value", "value": 120 }, { "code": "colour_data", "custom_name": "", "dp_id": 24, "time": 1725188137445, "type": "string", "value": "0165033403e8" }, { "code": "countdown", "custom_name": "", "dp_id": 26, "time": 1719734380289, "type": "value", "value": 0 }, { "code": "music_data", "custom_name": "", "dp_id": 27, "time": 1667128527761, "type": "string", "value": "" }, { "code": "control_data", "custom_name": "", "dp_id": 28, "time": 1667128527761, "type": "string", "value": "" }, { "code": "debug_data", "custom_name": "", "dp_id": 29, "time": 1667128527761, "type": "string", "value": "" }, { "code": "rhythm_mode", "custom_name": "", "dp_id": 30, "time": 1725647849201, "type": "raw", "value": "AAAAAAA=" }, { "code": "sleep_mode", "custom_name": "", "dp_id": 31, "time": 1725647849288, "type": "raw", "value": "AAA=" }, { "code": "wakeup_mode", "custom_name": "", "dp_id": 32, "time": 1725647849389, "type": "raw", "value": "AAA=" }, { "code": "power_memory", "custom_name": "", "dp_id": 33, "time": 1725647849689, "type": "raw", "value": "AAEAAAPoA+gD6APo" }, { "code": "do_not_disturb", "custom_name": "", "dp_id": 34, "time": 1719734380289, "type": "bool", "value": false }, { "code": "switch_gradient", "custom_name": "", "dp_id": 35, "time": 1725647849189, "type": "raw", "value": "AAAH0AAH0A==" }, { "code": "mix_light_scene", "custom_name": "", "dp_id": 36, "time": 1717790120840, "type": "raw", "value": "AAcAAAEGA0ZGAgAAA+gD6EZGAgB4A+gD6EZGAgDwA+gD6EZGAgA9A+gD6EZGAgCuA+gD6EZGAgETA+gD6A==" }, { "code": "remote_switch", "custom_name": "", "dp_id": 41, "time": 1667128527761, "type": "bool", "value": false }, { "code": "mix_rgbcw", "custom_name": "", "dp_id": 51, "time": 1725901545319, "type": "raw", "value": "AAUBZQM0A+gA0AB4" }, { "code": "segment_dimming", "custom_name": "", "dp_id": 52, "time": 1725647849107, "type": "raw", "value": "AAADAAAAAAAAA+gAAAAAAAAAAAPoAfQAAAAAAAAD6APo" }, { "code": "cycle_timing", "custom_name": "", "dp_id": 209, "time": 1725647849583, "type": "raw", "value": "AAAA" }, { "code": "random_timing", "custom_name": "", "dp_id": 210, "time": 1725647849489, "type": "raw", "value": "AAAA" } ] }

**Comment by bobvandevijver** [comment]
Can you please try version 1.3.1 (currently in test, https://homey.app/a/com.tuya/test) and check whether this issue persist?

**Comment by Riddler84** [comment]
> Can you please try version 1.3.1 (currently in test, https://homey.app/a/com.tuya/test) and check whether this issue persist?

Yes, that seems to solve the issue. Thanks.
