### ISSUE TITLE
Set fan speed on Wood's Cortina Silent 12K Smart Home

### ISSUE THREAD

**Issue by niikee94** [athombv/com.tuya#211]
### Homey version

Homey Pro 2016-2019 .  12.0.1

### Tuya app version

1.3.1

### App diagnostics report ID

a761b082-9bef-4c0c-b388-78a1b53da7b9

### Description

Hello. I have found a problem in the texline on my ac to send the spot value mid, which is now just a comma.
high and low works.
The problem is that even if I send the value "," the speed does not change. But it changes when sending text values ​​"higt" & "low"

Here is the line of text error I found on the developer page for the device:
\"fan_speed_enum\",\n \"desc\": \"{\\\"range\\\":[\\\"low\\\",\\\"high\\\"]}\ ",\n \"name\": \"风速电视

And the unit is a:
Wood's Cortina Silent 12K Smart Home

### Device specification

{ "device": { "active_time": 1721321655, "biz_type": 0, "category": "kt", "create_time": 1716490769, "icon": "smart/icon/ay1569237003624Hfrjq/13cf7e26f0b597360a6d1c8bebd17da4.png", "id": "bf7ba64ed7f46ac62fh7e9", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "AC", "name": "Wood's Cortina Silent 12K Smart Home", "online": true, "owner_id": "<redacted>", "product_id": "cyat7syhq4aqpicg", "product_name": "Wood's Cortina Silent 12K Smart Home", "status": [ { "code": "switch", "value": false }, { "code": "temp_set", "value": 20 }, { "code": "temp_current", "value": 19 }, { "code": "fan_speed_enum", "value": "high" }, { "code": "lock", "value": false }, { "code": "temp_unit_convert", "value": "c" }, { "code": "fault", "value": 0 }, { "code": "temp_current_f", "value": 50 }, { "code": "temp_set_f", "value": 62 }, { "code": "sleep", "value": false } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1722969603, "uuid": "<redacted>" }, "specifications": { "category": "kt", "functions": [ { "code": "switch", "desc": "{}", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "temp_set", "desc": "{\"unit\":\"℃\",\"min\":17,\"max\":30,\"scale\":0,\"step\":1}", "name": "设置温度", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":17,\"max\":30,\"scale\":0,\"step\":1}" }, { "code": "fan_speed_enum", "desc": "{\"range\":[\"low\",\"high\"]}", "name": "风速模式", "type": "Enum", "values": "{\"range\":[\"low\",\"high\"]}" }, { "code": "lock", "desc": "{}", "name": "童锁", "type": "Boolean", "values": "{}" }, { "code": "temp_unit_convert", "desc": "{\"range\":[\"c\",\"f\"]}", "name": "温标,华氏度，摄氏度切换新", "type": "Enum", "values": "{\"range\":[\"c\",\"f\"]}" }, { "code": "temp_set_f", "desc": "{\"unit\":\"℉\",\"min\":62,\"max\":86,\"scale\":0,\"step\":1}", "name": "设置华氏温度", "type": "Integer", "values": "{\"unit\":\"℉\",\"min\":62,\"max\":86,\"scale\":0,\"step\":1}" }, { "code": "sleep", "desc": "{}", "name": "睡眠功能", "type": "Boolean", "values": "{}" } ], "status": [ { "code": "switch", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "temp_set", "name": "设置温度", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":17,\"max\":30,\"scale\":0,\"step\":1}" }, { "code": "temp_current", "name": "当前温度", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":10,\"max\":35,\"scale\":0,\"step\":1}" }, { "code": "fan_speed_enum", "name": "风速模式", "type": "Enum", "values": "{\"range\":[\"low\",\"high\"]}" }, { "code": "lock", "name": "童锁", "type": "Boolean", "values": "{}" }, { "code": "temp_unit_convert", "name": "温标,华氏度，摄氏度切换(新)", "type": "Enum", "values": "{\"range\":[\"c\",\"f\"]}" }, { "code": "fault", "name": "故障告警", "type": "Bitmap", "values": "{\"label\":[\"sensor_fault\",\"temp_fault\"]}" }, { "code": "temp_current_f", "name": "当前华氏温度", "type": "Integer", "values": "{\"unit\":\"℉\",\"min\":50,\"max\":95,\"scale\":0,\"step\":1}" }, { "code": "temp_set_f", "name": "设置华氏温度", "type": "Integer", "values": "{\"unit\":\"℉\",\"min\":62,\"max\":86,\"scale\":0,\"step\":1}" }, { "code": "sleep", "name": "睡眠功能", "type": "Boolean", "values": "{}" } ] } }
Energy

**Comment by bobvandevijver** [comment]
As indicated in the specification your device only supports `low` and `high` for the fan speed..
