### ISSUE TITLE
Problem Flow Tag

### ISSUE THREAD

**Issue by HPLvanM** [athombv/com.tuya#216]
### Homey version

Homey Pro (Early 2023) 12.0.2

### Tuya app version

Tuya v1.3.1

### App diagnostics report ID

oops, it looks like this app is on fire

### Description

![Problem and Flow Tag](https://github.com/user-attachments/assets/52cef4f6-116d-46e2-bb9c-3457604e7ba5)
top en botom flow in the image don't give the same result?
The #StartValue is 61 (Yellow) does not give the correct result!

**Comment by bobvandevijver** [comment]
You will need to use a value between 0 and 1 if you use a number tag, so, instead of 61 you will need to use ~0.169.
