### ISSUE TITLE
[Device request]: WiFi smart online 5 in 1 tester

### ISSUE THREAD

**Issue by pinpoint90** [athombv/com.tuya#219]
### Device information

WiFi smart online 5 in 1 tester, tuya iot device id:    bf7714a8aae31d2a9ftapb
Also goes by "Yieryi Tuya WIFI Smart PH Meter", brand name yieryi, model YY-W9909

[https://vi.aliexpress.com/item/1005006200292096.html?spm=a2g0o.order_list.order_list_main.44.6ff21802mM4A96&gatewayAdapt=glo2vnm](url)

### Device specification

The WIFI device cannot be added to homey at all. It even can`t be added with Tuya Cloud app

**Comment by bobvandevijver** [comment]
Closing this as the device specification is missing, and it seems you are using the wrong app.

**Comment by pinpoint90** [comment]
I`m sorry, I manged to get the device specifications:

{ "device": { "active_time": 1724520736, "biz_type": 0, "category": "dgnbj", "create_time": 1724520736, "icon": "smart/icon/bay1620787138798I6P6/a62d5fea4cf9a7f4498f7ffd81bdedcd.png", "id": "bf7714a8aae31d2a9ftapb", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "", "name": "WiFi smart online 5 in 1 tester", "online": true, "owner_id": "<redacted>", "product_id": "qajfz5x1lqej5xxw", "product_name": "WiFi smart online 5 in 1 tester", "status": [ { "code": "temp_current", "value": 228 } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1726126754, "uuid": "<redacted>" }, "specifications": { "category": "dgnbj", "functions": [], "status": [ { "code": "temp_current", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-100,\"max\":1100,\"scale\":1,\"step\":1}" } ] }, "data_points": [ { "code": "temp_current", "custom_name": "", "dp_id": 8, "time": 1726129409479, "type": "value", "value": 228 }, { "code": "sensor_list", "custom_name": "", "dp_id": 101, "time": 1726129409268, "type": "raw", "value": "AQEBAQABAA==" }, { "code": "ph_current", "custom_name": "", "dp_id": 102, "time": 1726129409659, "type": "value", "value": 891 }, { "code": "ph_warn_max", "custom_name": "", "dp_id": 103, "time": 1726126756660, "type": "value", "value": 0 }, { "code": "ph_warn_min", "custom_name": "", "dp_id": 104, "time": 1726126756660, "type": "value", "value": 0 }, { "code": "temp_warn_max", "custom_name": "", "dp_id": 105, "time": 1726126756896, "type": "value", "value": 0 }, { "code": "temp_warn_min", "custom_name": "", "dp_id": 106, "time": 1726126756660, "type": "value", "value": 0 }, { "code": "tds_current", "custom_name": "", "dp_id": 107, "time": 1726129403363, "type": "value", "value": 35400 }, { "code": "tds_warn_max", "custom_name": "", "dp_id": 108, "time": 1726126754764, "type": "value", "value": 0 }, { "code": "tds_warn_min", "custom_name": "", "dp_id": 109, "time": 1726126754855, "type": "value", "value": 0 }, { "code": "ec_current", "custom_name": "", "dp_id": 110, "time": 1726129406827, "type": "value", "value": 70900 }, { "code": "ec_warn_max", "custom_name": "", "dp_id": 111, "time": 1726126755038, "type": "value", "value": 0 }, { "code": "ec_warn_min", "custom_name": "", "dp_id": 112, "time": 1726126755132, "type": "value", "value": 0 }, { "code": "salinity_current", "custom_name": "", "dp_id": 113, "time": 1726129407086, "type": "value", "value": 41300 }, { "code": "salinity_warn_max", "custom_name": "", "dp_id": 114, "time": 1726126755314, "type": "value", "value": 0 }, { "code": "salinity_warn_min", "custom_name": "", "dp_id": 115, "time": 1726126761412, "type": "value", "value": 0 }, { "code": "pro_current", "custom_name": "", "dp_id": 116, "time": 1726129407425, "type": "value", "value": 1038 }, { "code": "pro_warn_max", "custom_name": "", "dp_id": 117, "time": 1724520736560, "type": "value", "value": 500 }, { "code": "pro_warn_min", "custom_name": "", "dp_id": 118, "time": 1724520736560, "type": "value", "value": 500 }, { "code": "orp_current", "custom_name": "", "dp_id": 119, "time": 1726129407720, "type": "value", "value": 0 }, { "code": "orp_warn_max", "custom_name": "", "dp_id": 120, "time": 1726126756192, "type": "value", "value": 0 }, { "code": "orp_warn_min", "custom_name": "", "dp_id": 121, "time": 1726126756328, "type": "value", "value": 0 }, { "code": "cf_current", "custom_name": "", "dp_id": 136, "time": 1724520736560, "type": "value", "value": 0 }, { "code": "cf_warn_max", "custom_name": "", "dp_id": 137, "time": 1724520736560, "type": "value", "value": 0 }, { "code": "cf_warn_min", "custom_name": "", "dp_id": 138, "time": 1724520736560, "type": "value", "value": 1 }, { "code": "rh_current", "custom_name": "", "dp_id": 139, "time": 1724520736560, "type": "value", "value": 0 }, { "code": "rh_warn_max", "custom_name": "", "dp_id": 140, "time": 1724520736560, "type": "value", "value": 0 }, { "code": "rh_warn_min", "custom_name": "", "dp_id": 141, "time": 1724520736560, "type": "value", "value": 0 } ] }
