### ISSUE TITLE
[Device Request]: Tuya roller blinds motor 

### ISSUE THREAD

**Issue by baloe1541** [athombv/com.tuya#22]
To request a new device, please run the Tuya app locally using Homey CLI.

https://a.aliexpress.com/_EIUtQiR

Have 4 of these devices 

"device": { "active_time": [1666898568](tel:1666898568), "biz_type": 0, "category": "cl", "create_time": [1593889745](tel:1593889745), "icon": "smart/program_category_icon/cl.png", "id": "31381150cc50e3ff0594", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "CCB-11", "name": "Rolgordijn keuken ", "online": false, "owner_id": "<redacted>", "product_id": "3r8gc33pnqsxfe1g", "product_name": "Blinds Controller", "status": [ { "code": "control", "value": "stop" }, { "code": "percent_control", "value": 0 }, { "code": "percent_state", "value": 0 }, { "code": "control_back", "value": false }, { "code": "work_state", "value": "opening" }, { "code": "countdown", "value": "cancel" }, { "code": "countdown_left", "value": 0 }, { "code": "time_total", "value": 32627 } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": [1713106059](tel:1713106059), "uuid": "<redacted>" }, "specifications": { "category": "cl", "functions": [ { "code": "control", "desc": "{\"range\":[\"open\",\"stop\",\"close\"]}", "name": "控制", "type": "Enum", "values": "{\"range\":[\"open\",\"stop\",\"close\"]}" }, { "code": "percent_control", "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "name": "开启百分比控制", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "control_back", "desc": "{}", "name": "换向操作", "type": "Boolean", "values": "{}" }, { "code": "countdown", "desc": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}", "name": "倒计时", "type": "Enum", "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}" } ], "status": [ { "code": "control", "name": "控制", "type": "Enum", "values": "{\"range\":[\"open\",\"stop\",\"close\"]}" }, { "code": "percent_control", "name": "开启百分比控制", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "percent_state", "name": "开启百分比状态", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "control_back", "name": "换向操作", "type": "Boolean", "values": "{}" }, { "code": "work_state", "name": "工作状态", "type": "Enum", "values": "{\"range\":[\"opening\",\"closing\"]}" }, { "code": "countdown", "name": "倒计时", "type": "Enum", "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}" }, { "code": "countdown_left", "name": "倒计时剩余时间", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "time_total", "name": "全程运行时间", "type": "Integer", "values": "{\"unit\":\"ms\",\"min\":0,\"max\":120000,\"scale\":0,\"step\":1}" } ] } }

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by baloe1541** [comment]
I only see this 
![IMG_9013](https://github.com/user-attachments/assets/bcee7dd1-9e1b-4e6e-84a4-6dfa33d0ce16)

**Comment by bobvandevijver** [comment]
There is more information in that field, but it is not fully shown on mobile. It is easier to copy all information using the webapp at https://my.homey.app. Just keep clicking the content until it is selected.

**Comment by baloe1541** [comment]
Check !

"device": { "active_time": [1666898568](tel:1666898568), "biz_type": 0, "category": "cl", "create_time": [1593889745](tel:1593889745), "icon": "smart/program_category_icon/cl.png", "id": "31381150cc50e3ff0594", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "CCB-11", "name": "Rolgordijn keuken ", "online": false, "owner_id": "<redacted>", "product_id": "3r8gc33pnqsxfe1g", "product_name": "Blinds Controller", "status": [ { "code": "control", "value": "stop" }, { "code": "percent_control", "value": 0 }, { "code": "percent_state", "value": 0 }, { "code": "control_back", "value": false }, { "code": "work_state", "value": "opening" }, { "code": "countdown", "value": "cancel" }, { "code": "countdown_left", "value": 0 }, { "code": "time_total", "value": 32627 } ], "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": [1713106059](tel:1713106059), "uuid": "<redacted>" }, "specifications": { "category": "cl", "functions": [ { "code": "control", "desc": "{\"range\":[\"open\",\"stop\",\"close\"]}", "name": "控制", "type": "Enum", "values": "{\"range\":[\"open\",\"stop\",\"close\"]}" }, { "code": "percent_control", "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "name": "开启百分比控制", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "control_back", "desc": "{}", "name": "换向操作", "type": "Boolean", "values": "{}" }, { "code": "countdown", "desc": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}", "name": "倒计时", "type": "Enum", "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}" } ], "status": [ { "code": "control", "name": "控制", "type": "Enum", "values": "{\"range\":[\"open\",\"stop\",\"close\"]}" }, { "code": "percent_control", "name": "开启百分比控制", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "percent_state", "name": "开启百分比状态", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "control_back", "name": "换向操作", "type": "Boolean", "values": "{}" }, { "code": "work_state", "name": "工作状态", "type": "Enum", "values": "{\"range\":[\"opening\",\"closing\"]}" }, { "code": "countdown", "name": "倒计时", "type": "Enum", "values": "{\"range\":[\"cancel\",\"1\",\"2\",\"3\",\"4\"]}" }, { "code": "countdown_left", "name": "倒计时剩余时间", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" }, { "code": "time_total", "name": "全程运行时间", "type": "Integer", "values": "{\"unit\":\"ms\",\"min\":0,\"max\":120000,\"scale\":0,\"step\":1}" } ] } }

**Comment by baloe1541** [comment]
@bobvandevijver is it okay

**Comment by bobvandevijver** [comment]
Yes, this is indeed what we are looking for, thank you!
