### ISSUE TITLE
[Device request]: Tuya WIFI outdoor Power plug WIFIPO120FWT

### ISSUE THREAD

**Issue by pinpoint90** [athombv/com.tuya#223]
### Device information

WIFI outdoor on/off plug, model WIFIPO120FWT
Also under brand Nedis WIFIPO120FWT

[https://nedis.com/en-us/product/smart-home/energy/smart-plugs/550710067/smartlife-smart-plug-wi-fi-ip44-power-meter-3680-w-plug-with-earth-contact-type-f-cee-77-30-40-0c-android-ios-grey-white-1-pcs](https://github.com/athombv/com.tuya/issues/url)

### Device specification

{ "device": { "active_time": 1707240906, "biz_type": 0, "category": "cz", "create_time": 1612368263, "icon": "smart/device_icon/eu1600522277055ANRtQ/70711233a4cf12ec428c167074022707840.png", "id": "70711233a4cf12ec428c", "ip": "", "lat": "", "local_key": "", "lon": "", "model": "WIFIPO120FWT", "name": "Bilvarmer", "online": true, "owner_id": "", "product_id": "dbieebqj8teqxt1w", "product_name": "Smart Plug", "status": [ { "code": "switch", "value": false }, { "code": "countdown_1", "value": 0 }, { "code": "cur_current", "value": 0 }, { "code": "cur_power", "value": 0 }, { "code": "cur_voltage", "value": 2341 } ], "sub": false, "time_zone": "+01:00", "uid": "", "update_time": 1726126774, "uuid": "" }, "specifications": { "category": "cz", "functions": [ { "code": "switch", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "type": "Integer", "values": "{"unit":"s","min":0,"max":86400,"scale":0,"step":1}" } ], "status": [ { "code": "switch", "type": "Boolean", "values": "{}" }, { "code": "cur_current", "type": "Integer", "values": "{"unit":"mA","min":0,"max":30000,"scale":0,"step":1}" }, { "code": "cur_power", "type": "Integer", "values": "{"unit":"W","min":0,"max":50000,"scale":0,"step":1}" }, { "code": "cur_voltage", "type": "Integer", "values": "{"unit":"V","min":0,"max":2500,"scale":0,"step":1}" }, { "code": "countdown_1", "type": "Integer", "values": "{"unit":"s","min":0,"max":86400,"scale":0,"step":1}" } ] }, "data_points": [ { "code": "switch_on", "custom_name": "", "dp_id": 1, "time": 1725203355731, "type": "bool", "value": false }, { "code": "countdown", "custom_name": "", "dp_id": 2, "time": 1725193554280, "type": "value", "value": 0 }, { "code": "add_ele", "custom_name": "", "dp_id": 3, "time": 1726127805000, "type": "value", "value": 1 }, { "code": "cur_current", "custom_name": "", "dp_id": 4, "time": 1726121281336, "type": "value", "value": 0 }, { "code": "cur_power", "custom_name": "", "dp_id": 5, "time": 1726121281336, "type": "value", "value": 0 }, { "code": "cur_voltage", "custom_name": "", "dp_id": 6, "time": 1726128481614, "type": "value", "value": 2341 } ] }

**Comment by bobvandevijver** [comment]
This device is already supported, you can add it as a socket.

**Comment by pinpoint90** [comment]
The app finds all my other sockets, but not this particular one.
