### ISSUE TITLE
Deltaco Smartplug SH-P01

### ISSUE THREAD

**Issue by Hangon-wolfman** [athombv/com.tuya#226]
### Homey version

homey pro 2023 version 12.0.1

### Tuya app version

1.3.1

### Description

the one problem is that I can't control my smart plugs from (Deltaco Smartplug SH-P01) via the tuya app
But I can control the (Deltaco SH-P02E) smart which has two plugs in tuya app on homey

**Comment by bobvandevijver** [comment]
Without the device specification and a detailed description of what is happening we cannot help you.

**Comment by Hangon-wolfman** [comment]
![ScreenHunter 145](https://github.com/user-attachments/assets/f2f3b13a-c8e8-4b34-9078-e7af957b7c58)
it is found in smartlife app but not in homey
Device specification look picture

**Comment by bobvandevijver** [comment]
If it shows <not available> you can either re-add your device, or add it as other/unknown to retrieve the correct value. Also, please do not use an image when posting the specification.

**Comment by Hangon-wolfman** [comment]
from tuya Developer platform device id 05035760d8f15bdb85fe

**Comment by bobvandevijver** [comment]
That is not the device specification that we need. I am locking this issue: you can create a new ticket, which clearly explains how to retrieve the specification.
