### ISSUE TITLE
[Device request]: Tuya Zigbee/Bluetooth gateway

### ISSUE THREAD

**Issue by pinpoint90** [athombv/com.tuya#228]
### Device information

Nedis WIFIZBT10CWT

https://nedis.no/no-no/product/smarthus/styre/gateways/550783945/smartlife-gateway-bluetooth-zigbee-3-0-50-enheter-nettstroem-drevet-android-ios-hvit

### Device specification

{ "device": { "active_time": 1709390053, "biz_type": 0, "category": "wg2", "create_time": 1709390053, "icon": "smart/icon/ay1513237774906SMBA3/af45696c825cb3cb88c6396d51a33aba.png", "id": "bf9a9063816ba27eecipwf", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "WIFIZBT10CWT", "name": "Zigbee-gateway", "online": true, "owner_id": "<redacted>", "product_id": "8cwgjybjqmesflcz", "product_name": "Zigbee Gateway", "status": [ { "code": "switch_alarm_sound", "value": false }, { "code": "master_state", "value": "normal" }, { "code": "factory_reset", "value": false }, { "code": "alarm_active", "value": "" } ], "sub": true, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1726189813, "uuid": "<redacted>" }, "specifications": { "category": "wg2", "functions": [ { "code": "switch_alarm_sound", "type": "Boolean", "values": "{}" }, { "code": "master_state", "type": "Enum", "values": "{\"range\":[\"normal\",\"alarm\"]}" }, { "code": "factory_reset", "type": "Boolean", "values": "{}" }, { "code": "alarm_active", "type": "String", "values": "{\"maxlen\":255}" } ], "status": [ { "code": "switch_alarm_sound", "type": "Boolean", "values": "{}" }, { "code": "master_state", "type": "Enum", "values": "{\"range\":[\"normal\",\"alarm\"]}" }, { "code": "factory_reset", "type": "Boolean", "values": "{}" }, { "code": "alarm_active", "type": "String", "values": "{\"maxlen\":255}" } ] }, "data_points": [ { "code": "switch_alarm_sound", "custom_name": "", "dp_id": 4, "time": 1725152765642, "type": "bool", "value": false }, { "code": "master_state", "custom_name": "", "dp_id": 32, "time": 1725152765642, "type": "enum", "value": "normal" }, { "code": "factory_reset", "custom_name": "", "dp_id": 34, "time": 1709390053224, "type": "bool", "value": false }, { "code": "alarm_active", "custom_name": "", "dp_id": 45, "time": 1709390053224, "type": "string", "value": "" } ] }

**Comment by bobvandevijver** [comment]
This app won't be supporting the gateway devices, because that isn't necessary. Devices connected through that gateway can be added separately, and is there is anything on the gateway itself you want to control you can use the generic flows cards.
