### ISSUE TITLE
Devices not updating after initial state

### ISSUE THREAD

**Issue by feeloor** [athombv/com.tuya#235]
### Homey version

2023 Homey Pro, 12.0.2

### Tuya app version

1.3.3

### App diagnostics report ID

1d535874-67ac-4eaf-b1ef-cb252453df95

### Description

I have multiple devices connected which are having issues updating. They are updated when I restart the app but they are not receiving any updates after that. 
One contact sensor and one vibration sensor (which I connected using "other").

I've setup a testing flow with multiple triggers on both the vibration sensor but also the contact sensor. None of them are triggering and on my contact sensor it says that last state change was more than a month ago.

I'll attach picture of my flow, it has both built in triggers but also the webhook triggers and none of them are working.

<img width="843" alt="Skärmavbild 2024-09-16 kl  16 59 30" src="https://github.com/user-attachments/assets/6cde39ef-590b-4f48-9efe-e4e95e2dace4">

This issue is related to #166. 

### Device specification

Vibration sensor
```
{ "device": { "active_time": 1724700240, "biz_type": 0, "category": "zd", "create_time": 1724410500, "icon": "smart/icon/ay1576116878587LZIVo/7ff3f556d76980ac3c197b62ffcc742b.png", "id": "bf77974f98a56a0567ptsa", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "vibrate", "name": "Postlåda", "online": true, "owner_id": "<redacted>", "product_id": "koxpjd1znlbdacnf", "product_name": "震动传感器", "status": [ { "code": "shock_state", "value": "normal" }, { "code": "battery_state", "value": "high" }, { "code": "battery_percentage", "value": 100 }, { "code": "sensitivity", "value": 7 } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1726291318, "uuid": "<redacted>" }, "specifications": { "category": "zd", "functions": [ { "code": "sensitivity", "type": "Integer", "values": "{\"unit\":\"\",\"min\":0,\"max\":9,\"scale\":0,\"step\":1}" } ], "status": [ { "code": "shock_state", "type": "Enum", "values": "{\"range\":[\"normal\",\"vibration\",\"drop\"]}" }, { "code": "battery_state", "type": "Enum", "values": "{\"range\":[\"low\",\"middle\",\"high\"]}" }, { "code": "battery_percentage", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "sensitivity", "type": "Integer", "values": "{\"unit\":\"\",\"min\":0,\"max\":9,\"scale\":0,\"step\":1}" } ] }, "data_points": "<not available>" }
```

Contact sensor
```
{ "device": { "active_time": 1724753277, "biz_type": 0, "category": "mcs", "create_time": 1724753277, "icon": "smart/icon/ay1574490117625MIxZY/fa22e30b32b420105d0d6090fdd93c39.png", "id": "bfddf1adc193274895lrw5", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "Door Sensor", "name": "Contact Sensor", "online": true, "owner_id": "<redacted>", "product_id": "g2uishoy2nasxgz0", "product_name": "Contact Sensor", "status": [ { "code": "doorcontact_state", "value": false }, { "code": "battery_percentage", "value": 100 } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1724753372, "uuid": "<redacted>" }, "specifications": { "category": "mcs", "functions": [], "status": [ { "code": "doorcontact_state", "type": "Boolean", "values": "{}" }, { "code": "battery_percentage", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" } ] }, "data_points": "<not available>" }`

**Comment by bobvandevijver** [comment]
I'm seeing the same permission errors in you log as in #230. Did you use this account with the old Tuya Cloud app by any chance?

If so, can you try to create a fresh Tuya account?

**Comment by feeloor** [comment]
@bobvandevijver I did try to create a new one. I tried both an old Tuya Smart account, Smart Life account after none of them worked I tried to create a completely new one

**Comment by bobvandevijver** [comment]
Running the app yourself should not be any issue. When moving the device to the new account, did you use "Remove" or "Remove and clear data"? The latter is required for it to receive a new device identifier, which might be the catch here.

**Comment by feeloor** [comment]
@bobvandevijver I'm not completely sure, I deleted one of my old Tuya Smart account and still have the SmartLife account, is there a way for me to verify?

**Comment by bobvandevijver** [comment]
Only if you know the device id that was used for the device. But to be sure I would like to ask to redo this anyways then, make sure to remove the device with the clear data option, and re-add id. The device id should have changed (it is now `bf77974f98a56a0567ptsa` for your vibration sensor). I am curious whether that changes anything.

**Comment by feeloor** [comment]
Okay, I will give it a try and report back.

**Comment by feeloor** [comment]
I tried to remove it and re-added it and I can confirm it has a new ID now (bf4f1dd6e0db0a07a1ioup). However I still don't get any notifications in the flow (which I also updated with the new device).

**Comment by feeloor** [comment]
I've sent you an invitation for the device. The strange thing is that it's the exact same with my contact sensor. It's also not receiving any updates. Let me know if I can assist in anyway in debugging.

**Comment by bobvandevijver** [comment]
Something went wrong with that invite, can you please try again? Copying the link works better in my experience.

**Comment by bobvandevijver** [comment]
Quick update: the issue seems to be on the Tuya cloud side but it is currently unknown why. I have forwarded it to one of our contacts to look into, but unfortunately I do not have any ETA on an answer and/or solution at this time.

**Comment by feeloor** [comment]
Okay, thank you for the update. Please let me know if there is anything I can do to assist.

**Comment by bobvandevijver** [comment]
The source of this issue has been found on the Tuya cloud side: they are working on a solution and hopefully this issue should fix itself somewhere next week for existing users.

It might be the case that a device repair solves the issue already, so you can try that. Otherwise you will have to wait until it is fixed on the cloud side.

**Comment by feeloor** [comment]
Thats great news, thank for the update! 👍

**Comment by feeloor** [comment]
I can confirm this is now working, both for my vibration sensor as well as the contact sensor. Thanks for the assistance and quick solving! @bobvandevijver
