### ISSUE TITLE
[Device request]: Smart Mouse Trap

### ISSUE THREAD

**Issue by HenkLaracker** [athombv/com.tuya#237]
### Device information

https://nl.aliexpress.com/item/10000128709589.html?spm=a2g0o.productlist.main.1.1c3d7041SoO5tW&algo_pvid=429d3904-6c24-4199-b717-2461726cbd77&algo_exp_id=429d3904-6c24-4199-b717-2461726cbd77-0&pdp_npi=4%40dis%21EUR%2136.21%2134.69%21%21%2138.42%2136.81%21%40211b80d117209884157248992e2211%2120000000124861947%21sea%21NL%21752668917%21&curPageLogUid=2goLt5ByKISr&utparam-url=scene%3Asearch%7Cquery_from%3A

### Device specification

```json
{
  "device": {
    "active_time": 1710784520,
    "biz_type": 18,
    "category": "qt",
    "create_time": 1710784520,
    "icon": "smart/icon/15379312134ju2oarqmew_0.png",
    "id": "61125160c8c9a3222440",
    "ip": "",
    "lat": "",
    "local_key": "",
    "lon": "",
    "model": "",
    "name": "Smart Mouser",
    "online": true,
    "owner_id": "",
    "product_id": "oAhphrO8qMU8RU7Y",
    "product_name": "Smart Mouser",
    "sub": false,
    "time_zone": "+01:00",
    "uid": "",
    "update_time": 1726494882,
    "uuid": "",
    "status": []
  },
  "specifications": "",
  "data_points": [
    {
      "code": "Mouse",
      "custom_name": "",
      "dp_id": 101,
      "time": 1726494882598,
      "type": "bool",
      "value": false
    },
    {
      "code": "BatteryStatus",
      "custom_name": "",
      "dp_id": 102,
      "time": 1726494882641,
      "type": "enum",
      "value": "0x00"
    }
  ]
}
```

**Comment by bobvandevijver** [comment]
Unfortunately, your device has not been configured by its manufacturer to use the standard status set, which means we will not support it natively. You can still control it using the general flow cards provided with the "other" device type.
