### ISSUE TITLE
Request Device: Scene Switch - Moes Star Ring Grey 3-Gang Scene Switch

### ISSUE THREAD

**Issue by deejayreissue** [athombv/com.tuya#24]
Can you add this device?

https://moeshouse.com/products/eu-star-ring-smart-light-switch-1

3-Gang version

`2024-06-16T17:52:39.760Z [log] [ManagerDrivers] [Driver:other] Device: {"active_time":1717261450,"biz_type":18,"category":"wxkg","create_time":1717252796,"icon":"smart/icon/ay1468288548509686pw/2475ef9c4e238d08914c21c2f9e6e87e.png","id":"bfd6ab736b744dc847mwfp","ip":"","lat":"XXXXX","local_key":"XXXXX","lon":"-XXXXX","model":"","name":"3 Gang ZigBee Scene Switch","node_id":"f4b3b1fffe1324a5","online":true,"owner_id":"XXXXXXXX","product_id":"gbm10jnj","product_name":"3 Gang ZigBee Scene Switch","status":[{"code":"switch1_value","value":"single_click"},{"code":"switch_mode2","value":"click"},{"code":"switch_mode3","value":"click"}],"sub":true,"time_zone":"+01:00","uid":"XXXXX","update_time":1718061607,"uuid":"XXXXX"}`

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by deejayreissue** [comment]
> We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

Not possible.

When I add these devices to the app as 'Other' Tuya devices, the device specification is blank.

**Comment by bobvandevijver** [comment]
Closing this due to missing info. If still relevant, please open a new issue and provide the information as described in the templates.
