### ISSUE TITLE
Request Device: Scene Switch - CRYSTAL+ Touch Wifi Switch 3Gang

### ISSUE THREAD

**Issue by deejayreissue** [athombv/com.tuya#25]
Hey,

Could you add this device please?

https://www.retrotouch.co.uk/wi-fi-smart-touch-light-switches/crystal-touch-wifi-switch-3g-grey.html

`2024-06-16T17:52:39.763Z [log] [ManagerDrivers] [Driver:other] Device: {"active_time":1683306399,"biz_type":18,"category":"kg","create_time":1683306399,"icon":"smart/icon/ay1544258518257utIpI/1654789547ba3be194688.jpg","id":"bf3b9fdb3ce58800eemmo4","ip":"XXXXX","lat":"XXXXX","local_key":"XXXXX","lon":"XXXXX","model":"01072","name":"Bathroom Light Switch","online":true,"owner_id":"XXXXX","product_id":"v9cvcs08mwervp0g","product_name":"Crystal+ Touch WiFi 3G `Switch","status":[{"code":"switch_1","value":false},{"code":"switch_2","value":false},{"code":"switch_3","value":false},{"code":"countdown_1","value":0},{"code":"countdown_2","value":0},{"code":"countdown_3","value":0},{"code":"relay_status","value":"last"},{"code":"switch_backlight","value":true},{"code":"cycle_time","value":""},{"code":"random_time","value":""},{"code":"switch_inching","value":""}],"sub":false,"time_zone":"+01:00","uid":"XXXXX","update_time":1718061603,"uuid":"XXXXX``

**Comment by bobvandevijver** [comment]
Support for this device category has already been added, it should become available soon.

**Comment by deejayreissue** [comment]
Hey,

I've seen nothing on the forum thread or on the app to suggest that Switches are now supported by the new Tuya app?

**Comment by bobvandevijver** [comment]
As mentioned and now tagged, it will become available once release 1.2.0 becomes available. We hope to have that version in test somewhere this week.
