### ISSUE TITLE
Denver Power Strip is offline

### ISSUE THREAD

**Issue by jeverhjem** [athombv/com.tuya#257]
### Homey version

Homey Pro (Early 2023), 12.0.2

### Tuya app version

5.17.2

### App diagnostics report ID

6f9c6bcd-7c76-4ddb-a334-31999872e937

### Description

The Denver Power Strip has status offline, but in the Tuya App it is working fine

Homey Pro Tuya app version 1.3.5

### Device specification

{"device":{"active_time":1727189590,"biz_type":0,"category":"pc","create_time":1696243306,"icon":"smart/icon/ay1560928090236Hf5W0/ab6c1bfa043f99f93e6e70e90d2837b4.png","id":"1702537170039f2aaa15","ip":"<redacted>","lat":"<redacted>","local_key":"<redacted>","lon":"<redacted>","model":"DENVER SHP-310U","name":"Denver Power Strip 2","online":false,"owner_id":"<redacted>","product_id":"thyymhzm0f5wbjjq","product_name":"Denver SHP-310U Power Strip 3in1 + 2 USB","status":[{"code":"switch_1","value":false},{"code":"switch_2","value":false},{"code":"switch_3","value":false},{"code":"countdown_1","value":0},{"code":"countdown_2","value":0},{"code":"countdown_3","value":0}],"sub":false,"time_zone":"+01:00","uid":"<redacted>","update_time":1727363899,"uuid":"<redacted>"},"specifications":{"category":"pc","functions":[{"code":"switch_1","type":"Boolean","values":"{}"},{"code":"switch_2","type":"Boolean","values":"{}"},{"code":"switch_3","type":"Boolean","values":"{}"},{"code":"countdown_1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_2","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_3","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}],"status":[{"code":"switch_1","type":"Boolean","values":"{}"},{"code":"switch_2","type":"Boolean","values":"{}"},{"code":"switch_3","type":"Boolean","values":"{}"},{"code":"countdown_1","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_2","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"},{"code":"countdown_3","type":"Integer","values":"{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}"}]},"data_points":[{"code":"switch_1","custom_name":"","dp_id":1,"name":"Switch 1","time":1727360757862,"type":"bool","value":false},{"code":"switch_2","custom_name":"","dp_id":2,"name":"Switch 2","time":1727360757862,"type":"bool","value":false},{"code":"switch_3","custom_name":"","dp_id":3,"name":"Switch 3","time":1727360757862,"type":"bool","value":false},{"code":"countdown_1","custom_name":"","dp_id":9,"time":1727358351216,"type":"value","value":0},{"code":"countdown_2","custom_name":"","dp_id":10,"time":1727358351216,"type":"value","value":0},{"code":"countdown_3","custom_name":"","dp_id":11,"time":1727358351216,"type":"value","value":0}]}

**Comment by bobvandevijver** [comment]
According to the Tuya API (just checked) it is indeed offline, so it isn't connected to the cloud. You can try to turn it off/on, and you should check the cloud connection.

This is not an issue with the Homey app.
