### ISSUE TITLE
[Device Request]:  Air Humidifier Clean Air Optima CA-605

### ISSUE THREAD

**Issue by HenkRenting** [athombv/com.tuya#26]
Air Humidifier Clean Air Optima CA-605

```
2024-06-17T19:22:52.404Z [log] [ManagerDrivers] [Driver:light] Device: {"active_time":1703160435,"biz_type":0,"category":"jsq","create_time":1703160174,"icon":"smart/icon/bay1622636970661d2Uf/16563251498c2e8c02249.png","id":"bf2cf5e7a14025fa28fadm","ip":"62.131.100.126","lat":"52.2200","local_key":"a7z{8#2}~N|P##kA","lon":"6.9000","model":"CA-605B Smart","name":"Luchtbevochtiger","online":true,"owner_id":"176968438","product_id":"7mijurr4i9e0ewat","product_name":"Air Humidifier CA-605B Smart","sub":false,"time_zone":"+01:00","uid":"eu1703111454579AVBYc","update_time":1717461579,"uuid":"4f2f461398c9ff7a"}
```

Link to the manufacturer's website:
https://www.cleanairoptima.nl/humidifier-ca-605b
(the suffic "b" is for black, there is a titanium color too, with suffix "t", but it is technically the same.

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by HenkRenting** [comment]
Hi Bob,
Sure, here is the requested info:
`{ "device": { "active_time": 1703160435, "biz_type": 0, "category": "jsq", "create_time": 1703160174, "icon": "smart/icon/bay1622636970661d2Uf/16563251498c2e8c02249.png", "id": "bf2cf5e7a14025fa28fadm", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "CA-605B Smart", "name": "Luchtbevochtiger", "online": true, "owner_id": "<redacted>", "product_id": "7mijurr4i9e0ewat", "product_name": "Air Humidifier CA-605B Smart", "sub": false, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1723041915, "uuid": "<redacted>" }, "specifications": { "category": "jsq" } }`

**Comment by bobvandevijver** [comment]
It doesn't have any fields in the specification, so that isn't a great sign I'm afraid. We will have to investigate whether we can do anything with this device type.

**Comment by HenkRenting** [comment]
I have it already installed in the other Tuya Homey app, can control it and it sends data to Homey.
I'd be happy to supply more info. Just tell me what you need and I'd be happy to send you all you need.

**Comment by HenkRenting** [comment]
I see you removed “Missing info” and added “Confirmed”; does that mean you do have enough info, @bobvandevijver?
Otherwise the following might help?
(I would be more than happy to provide you with more info from the Tuya developer IoT site if you like…)

 from the JSON editor:
```
[
  {
    "code": "switch",
    "value": true
  },
  {
    "code": "sound",
    "value": false
  },
  {
    "code": "humidity_set",
    "value": 70
  },
  {
    "code": "sleep",
    "value": false
  },
  {
    "code": "temp_unit_convert",
    "value": "c"
  },
  {
    "code": "countdown_set",
    "value": "cancel"
  },
  {
    "code": "level",
    "value": "auto"
  },
  {
    "code": "anion",
    "value": false
  },
  {
    "code": "filter_reset",
    "value": false
  },
  {
    "code": "uv",
    "value": false
  }
]
```
Right screen under "Standard Instruction Set":
```
Code	Type	Values
switch	Boolean	
"{true,false}"
sound	Boolean	
"{true,false}"
humidity_set	Integer	
{
  "unit": "%",
  "min": 30,
  "max": 75,
  "scale": 0,
  "step": 5
}
sleep	Boolean	
"{true,false}"
temp_unit_convert	Enum	
{
  "range": [
    "c",
    "f"
  ]
}
countdown_set	Enum	
{
  "range": [
    "cancel",
    "1h",
    "2h",
    "3h",
    "4h",
    "5h",
    "6h",
    "7h",
    "8h",
    "9h",
    "10h",
    "11h",
    "12h"
  ]
}
level	Enum	
{
  "range": [
    "auto",
    "level1",
    "level2",
    "level3"
  ]
}
anion	Boolean	
"{true,false}"
filter_reset	Boolean	
"{true,false}"
uv	Boolean	
"{true,false}"

```
And "Standard Status Set" from the right screen:
```
switch	Boolean	
"{true,false}"
sound	Boolean	
"{true,false}"
temp_current	Integer	
{
  "unit": "℃",
  "min": -9,
  "max": 90,
  "scale": 0,
  "step": 1
}
temp_current_f	Integer	
{
  "unit": "℉",
  "min": 0,
  "max": 199,
  "scale": 0,
  "step": 1
}
humidity_set	Integer	
{
  "unit": "%",
  "min": 30,
  "max": 75,
  "scale": 0,
  "step": 5
}
humidity_current	Integer	
{
  "unit": "%",
  "min": 0,
  "max": 100,
  "scale": 0,
  "step": 1
}
sleep	Boolean	
"{true,false}"
temp_unit_convert	Enum	
{
  "range": [
    "c",
    "f"
  ]
}
countdown_set	Enum	
{
  "range": [
    "cancel",
    "1h",
    "2h",
    "3h",
    "4h",
    "5h",
    "6h",
    "7h",
    "8h",
    "9h",
    "10h",
    "11h",
    "12h"
  ]
}
countdown_left	Integer	
{
  "unit": "min",
  "min": 0,
  "max": 720,
  "scale": 0,
  "step": 1
}
fault	Bitmap	
{
  "label": [
    "lack_water"
  ],
  "maxlen": 1
}
level	Enum	
{
  "range": [
    "auto",
    "level1",
    "level2",
    "level3"
  ]
}
anion	Boolean	
"{true,false}"
filter_reset	Boolean	
"{true,false}"
filter_life	Integer	
{
  "unit": "%",
  "min": 0,
  "max": 100,
  "scale": 0,
  "step": 1
}
uv	Boolean	
"{true,false}"

```

**Comment by bobvandevijver** [comment]
@HenkRenting Can you please try to add the device as other device once again and see what happens when you try to control it using the manual code cards? Should look something like this:

![image](https://github.com/user-attachments/assets/19d88657-4930-47e8-939d-85a5eb42db5a)

There are four of these cards, can you check until you find one that shows a list?

**Comment by HenkRenting** [comment]
Sure, no problem @bobvandevijver.
Just to be sure; you ask it to be added as an "other" device; in the app I only have the option "unknown" (onbekend) device. So that is what I have done (perhaps a translate-glitch? :-))
I get an error for whatever of the four AND cards I try to use:
![image](https://github.com/user-attachments/assets/b1a82c02-0da8-403d-bc54-b3a6abce8be9)

**Comment by HenkRenting** [comment]
Perhaps the JSON of Jepke can help you out?
It is listed as humidifier (only one in there) in his fork of the community app:
https://github.com/jepke/com.tuya.cloud/tree/humidifier_henk/drivers/humidifier
[driver.compose.json](https://github.com/user-attachments/files/16549796/driver.compose.json)
[driver.settings.compose.json](https://github.com/user-attachments/files/16549797/driver.settings.compose.json)

**Comment by bobvandevijver** [comment]
Thanks for the confirmation, we will have to look into this a bit more (and hopefully find a device samples that behaves equally). If we need more information we will let you know!

**Comment by HenkRenting** [comment]
Thanks, @bobvandevijver.
If you like  I can lend you my device, as I only live about 500 meters from Oude Markt. Regularly at "Moeke", so... 😉

**Comment by HenkRenting** [comment]
No problem @bobvandevijver, although Capitool isn't far away either... ;)
I have just sent you the link by email.

**Comment by bobvandevijver** [comment]
Thank you for sharing the device with us. We have now seen where the difference comes from: Tuya devices internally use data points, which can be fully configured for each device and depends on whatever the manufacturer needs or wants. Next to that, Tuya offers a standard instruction/status set. But, in order to utilise the standard instructions/status information, a mapping with the data points must be made. It appears that that is either not done (for certain devices) or partially done. For the device you have this has not been done, which is why you get thew function not supported error with the flow cards.

We will be looking into exposing all data points through those flow cards. We will most probably not map it to Homey capabilities as we are using the standard sets for a good reason: they are the standard set related to a device category. But making the values available in flows is a great feature.

**Comment by vcebotari** [comment]
i have same issue for a device from `other` category

<img width="470" alt="Screenshot 2024-08-27 at 16 03 03" src="https://github.com/user-attachments/assets/1578f041-7d4f-4729-83dd-7e6c7e066efb">

autocomplete for codes gives nothing

on network tab i see request to this url `https://66cda00b9b5c276d0bd2ba8f.homey.prod-eucentral1-001.homeycloud.net/api/manager/flow/flowcardaction/homey:device:d161d144-8b67-460f-afa0-31a789fbe53f/homey:device:d161d144-8b67-460f-afa0-31a789fbe53f:send_command_boolean/autocomplete?name=code&query=switch&args%5Bcode%5D=undefined&args%5Bvalue%5D=undefined`

and the response is empty `[]`

can anyone help with that ? thanks

```

**Comment by bobvandevijver** [comment]
@vcebotari As already stated, that is something that will be fixed in an upcoming release.

**Comment by vcebotari** [comment]
thanks

**Comment by bobvandevijver** [comment]
Closing this particular ticket as there wont be coming a dedicated driver for this particular device, but discussing regarding the data point control can be continued in #166.
