### ISSUE TITLE
[Device request]: Tuya Zigbee Wireless scene switch

### ISSUE THREAD

**Issue by pinpoint90** [athombv/com.tuya#262]
### Device information

Tuya ZigBee Smart button
https://www.aliexpress.com/item/1005005941397190.html?spm=a2g0o.order_list.order_list_main.22.891d1802SOQThn

### Device specification

{"device":{"active_time":1727886425,"biz_type":0,"category":"wxkg","create_time":1727886425,"icon":"smart/icon/ay1547266640143rRUIA/c650ddbaa7e6d30b51ea677869266fcf.png","id":"bf455700d7c8722e537atp","ip":"<redacted>","lat":"<redacted>","local_key":"<redacted>","lon":"<redacted>","model":"","name":"Wireless scene switch","node_id":"a4c13805a1983e71","online":false,"owner_id":"<redacted>","product_id":"mrpevh8p","product_name":"Wireless scene switch","status":[{"code":"switch_mode1","value":"click"},{"code":"battery_percentage","value":100}],"sub":true,"time_zone":"+01:00","uid":"<redacted>","update_time":1727886594,"uuid":"<redacted>"},"specifications":{"category":"wxkg","functions":[],"status":[{"code":"switch_mode1","type":"Enum","values":"{\"range\":[\"click\",\"double_click\",\"press\"]}"},{"code":"battery_percentage","type":"Integer","values":"{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}"}]},"data_points":[{"code":"switch_type_1","custom_name":"","dp_id":1,"time":1727886425445,"type":"enum","value":"single_click"},{"code":"battery_percentage","custom_name":"","dp_id":10,"time":1727886430613,"type":"value","value":100}]}

**Comment by bobvandevijver** [comment]
This device is already supported with version 1.4.0, which is currently in testing.
