### ISSUE TITLE
Readings updates broken again

### ISSUE THREAD

**Issue by hrabbach** [athombv/com.tuya#276]
### Homey version

Home Pro (Early 2019), 12.1.0

### Tuya app version

1.4.1

### App diagnostics report ID

47570306-a761-492a-97b5-403a6104f5e3

### Description

The readings updates for T&H sensors that worked really well after the issue with the Tuya API servers was fixed a few weeks ago have suddenly stopped working again a few hours ago. Nothing changed - same app version, same Homey version, but sometime between 2 and 3 UTC, readings updates stopped. I can still get an updated reading by restarting the app, but then they don't update again after that.

**Comment by bobvandevijver** [comment]
There seems to be an issue with the message service at this time, we are looking into it.

**Comment by mruiter** [comment]
I see this issue marked as closed. But values still are not coming in . Wil there be a new version of the app.
Looked like it was a external cloud issue

**Comment by bobvandevijver** [comment]
This issue is not marked as closed. But no, there will not be a new version of the app as it is cloud related.

**Comment by mruiter** [comment]
Ah yes , on the phone browser is looks like closed but its the energy consumption #277 thats also mentioned in the thread as closed. Sorry

**Comment by bobvandevijver** [comment]
The relevant cloud component has been restored and updates should be coming in again. It might some time before we have catched up on all events, so please be patient 👍🏻

**Comment by gjb1969** [comment]
I have a probleem to ad T&H sensors that i could ad but of a remove one sensor in Homey i Can not ad it again
