### ISSUE TITLE
Thermostaat en humifiding device 

### ISSUE THREAD

**Issue by gjb1969** [athombv/com.tuya#280]
### Homey version

Homey pro (early 2919) 12.1.0

### Tuya app version

V1.4.1

### Description

I have several temperature gauges that worked fine at first. But at some point they didn't anymore so I thought I would remove them and try to reinstall them. But now they don't work anymore.

**Comment by bobvandevijver** [comment]
Without details (such as the diagnostics report and what you are seeing) it is almost impossible to help. Did you remove your devices from Homey or from the Tuya app? If you did the later, you will need to remove them from Homey as well, to re-add them afterwards.

**Comment by gjb1969** [comment]
> I removed the devices in Homey and also in tuya.
> And instaled iT again in tuya.
> And then tried to instal iT in Homey but iT dos not find the divice 
I still have one of the same devices that is working in Homey

**Comment by bobvandevijver** [comment]
If it isn't found you either already added it, or you have selected the wrong driver. Can't tell which, because you still did not share enough details and an app diagnostics report code.

**Comment by gjb1969** [comment]
92fc1f4e-f9e1-4e53-8157-510059df1c13

**Comment by bobvandevijver** [comment]
The report is not from when you were looking for new devices, but it looks like you have 4 sensors which should be found fine. So either you have already added them to Homey (can also be as other device) or you are doing something wrong. It can also help to restart the app.

**Comment by gjb1969** [comment]
It is working now thanks

**Comment by bobvandevijver** [comment]
Good to hear it works as it should.
