### ISSUE TITLE
20A smartplug with metering 

### ISSUE THREAD

**Issue by Jano1960** [athombv/com.tuya#285]
### Device information

![20241019_121728](https://github.com/user-attachments/assets/ac8963a7-b2c7-4cfc-91f8-9a7a1555248c)
![20241019_121745](https://github.com/user-attachments/assets/de5258a1-f5d3-4a44-ac8f-79d7cc255b4c)
![20241019_121718](https://github.com/user-attachments/assets/2a9d1861-abf6-4ca2-9e8d-b092bd16af3e)

### Device specification

![Screenshot_20241020-171820_Homey](https://github.com/user-attachments/assets/2df71856-4820-4629-abb3-c232714904ba)
![Screenshot_20241020-171828_Homey](https://github.com/user-attachments/assets/8b18f8c2-2e26-4f52-8778-c389f77dc488)
![Screenshot_20241020-171846_Homey](https://github.com/user-attachments/assets/4931a3fb-4766-4269-9cfd-181f4d4462d1)

**Comment by bobvandevijver** [comment]
This is a Zigbee device: this app only support WiFi/cloud connected device.
