### ISSUE TITLE
[Performance Issues] Extended values are long delayed or not getting in

### ISSUE THREAD

**Issue by mruiter** [athombv/com.tuya#287]
### Homey version

2023

### Tuya app version

Latest test

### Description

Extended values of the Tuya broadcasted messages are getting in late (20+ minutes late) or not at all.
Is there another cloud issue like 2 weeks ago ?

Reboot homey or restart app doesnt give any improvement

The community app messages come in straight away. Seems like a cloud connect issue of the Athom implementation of Tuya

**Comment by mruiter** [comment]
App diag id : d71359d6-e14a-484e-8800-796fadca6289

**Comment by bobvandevijver** [comment]
Can you share which datapoints and what the values are you're missing? From the report I am seeing more than enough data come in.

**Comment by mruiter** [comment]
For instance temp_bottom and temp_top is missing most of the time. 
I see it now processes values that where more then a hour ago online and processed correctly by the community app on time

Would be nice to see some kind of log windows of the values that come in the app

**Comment by mruiter** [comment]
At the moment the datapoint temp_top is getting values that are exactly 47 minutes and 12 seconds late

**Comment by bobvandevijver** [comment]
Is it better now?

**Comment by mruiter** [comment]
It differs. Datapoints temp_top and temp_bottom are still delayed . The datapoint venting_temp_f is instantly 
I have been monitoring a few minutes now . The venting is updated instant all the time the others two are still delayed.

**Comment by mruiter** [comment]
temp_top seems to be 1 hour late , temp_bottom is about 10 minutes late

**Comment by bobvandevijver** [comment]
Quite interesting... It feels like Tuya has scheduling issues with certain messages (and your device is generating a lot of messages by the way) as some are instant and others are delayed... We're seeing messages being queued, but for some reason they are not consumed while we seem to have enough capacity. Not sure there is anything we can do short term, but if we learn more I will let it know here.

**Comment by mruiter** [comment]
Yes , the device has a lot of datapoint. Only using 5 of them at the moment . 
Guess all datapoints are getting broadcasted even if they are not used by homey in flows and there is no way to unregister them.

The community app that uses the IOT Cloud of tuya itself doesnt have this issue :) But thats all on tuya its plaform so i guess they give that more priority

**Comment by bobvandevijver** [comment]
Yes, it is all or nothing. The community app uses a completely different Tuya service to receive the updates, so difference are to be expected.

**Comment by bobvandevijver** [comment]
Looking at the graphs it should be better now, can you confirm?

**Comment by mruiter** [comment]
Yes , atm it’s not instant but a few seconds late 3 to 10Verstuurd vanaf mijn iPhoneOp 25 okt 2024 om 16:56 heeft Bob van de Vijver ***@***.***> het volgende geschreven:﻿
Looking at the graphs it should be better now, can you confirm?
