### ISSUE TITLE
[Device request]: problem homey integration

### ISSUE THREAD

**Issue by stbeNala** [athombv/com.tuya#288]
### Device information

Hello, I have a big problem with a siren. I have already integrated Direne into Smartlife and Tuya on my cell phone and everything is fine here. If I integrate this into homey via the new official interface from tuya I get when I want to create a flow and finally: THEN siren on this is not available for selection. There is only this to choose from: (see picture) why is that? Thanks in advance!
![8c8070f451e5ed18225bcac03c82b7203eb024e0_2_1035x612](https://github.com/user-attachments/assets/dc0f6ad7-ec0c-41aa-bbe4-274f2ea987b2)
![8c8070f451e5ed18225bcac03c82b7203eb024e0_2_1035x612](https://github.com/user-attachments/assets/adf64085-a4b1-4ddf-b817-3dbdc956690b)

### Device specification

```json
{
  "device": {
    "active_time": 1729709917,
    "biz_type": 0,
    "category": "sgbj",
    "create_time": 1729709917,
    "icon": "smart/icon/ay1503986080106Gppjy/15c6f71b1ffe9b775fa4baf3585eb031.png",
    "id": "bf5c04ba6d293730c81xow",
    "ip": "<redacted>",
    "lat": "<redacted>",
    "local_key": "<redacted>",
    "lon": "<redacted>",
    "model": "",
    "name": "Siren",
    "online": true,
    "owner_id": "<redacted>",
    "product_id": "6c5kxwqmac6ceejz",
    "product_name": "Siren",
    "sub": false,
    "time_zone": "+02:00",
    "uid": "<redacted>",
    "update_time": 1729750322,
    "uuid": "<redacted>",
    "status": []
  },
  "specifications": "<not available>",
  "data_points": [
    {
      "code": "BatteryStatus",
      "custom_name": "",
      "dp_id": 101,
      "time": 1729750324793,
      "type": "enum",
      "value": "4"
    },
    {
      "code": "Alarmtype",
      "custom_name": "",
      "dp_id": 102,
      "time": 1729750324793,
      "type": "enum",
      "value": "12"
    },
    {
      "code": "AlarmPeriod",
      "custom_name": "",
      "dp_id": 103,
      "time": 1729750324793,
      "type": "value",
      "value": 10
    },
    {
      "code": "AlarmSwitch",
      "custom_name": "",
      "dp_id": 104,
      "time": 1729750324793,
      "type": "bool",
      "value": false
    }
  ]
}
```

**Comment by bobvandevijver** [comment]
Unfortunately your device has not been configured by the manufacturer to use the standard status set as it should, which means we cannot control it with the standard controls we offer. You can still use the offered flows to control it yourself. Use the first card, select the `AlarmSwitch` code and send a command with either `true` of `false` to toggle the siren.

**Comment by stbeNala** [comment]
Thanks for the quick reply. That's really a shame! I don't understand what I should enter in the first field? Which flow cards do I actually use? boolean or JSON? But what do I have to enter in the first field? in the second then true to start the siren?
