### ISSUE TITLE
Luminance Motion sensor

### ISSUE THREAD

**Issue by pinpoint90** [athombv/com.tuya#293]
### Homey version

Homey Pro 12.1.2

### Tuya app version

1.4.1

### Description

Ì`m using this device as a light sensor only. (there are two version of this device, one with light sensor and one without).
Is it possible to add fuction "when illuminance value reaches above or below a given value" then perform given action?
I can give access to my tuya device if required.

### Device specification

{ "device": { "active_time": 1730129233, "biz_type": 0, "category": "pir", "create_time": 1730129234, "icon": "smart/icon/ay1531985537002uUUZI/b96be71b30ff1babff8b299ffbbeab07.png", "id": "bf7c418aaabe50c7deawsm", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "ZG-204L", "name": "Luminance Motion sensor", "node_id": "a4c1388e1ceba858", "online": true, "owner_id": "<redacted>", "product_id": "3towulqd", "product_name": "Luminance Motion sensor ", "status": [ { "code": "pir", "value": "none" }, { "code": "battery_percentage", "value": 100 }, { "code": "pir_sensitivity", "value": "high" } ], "sub": true, "time_zone": "+01:00", "uid": "<redacted>", "update_time": 1730129234, "uuid": "<redacted>" }, "specifications": { "category": "pir", "functions": [ { "code": "pir_sensitivity", "type": "Enum", "values": "{\"range\":[\"low\",\"middle\",\"high\"]}" } ], "status": [ { "code": "pir", "type": "Enum", "values": "{\"range\":[\"pir\",\"none\"]}" }, { "code": "battery_percentage", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "pir_sensitivity", "type": "Enum", "values": "{\"range\":[\"low\",\"middle\",\"high\"]}" } ] }, "data_points": [ { "code": "pir_state", "custom_name": "", "dp_id": 1, "time": 1730129535300, "type": "enum", "value": "none" }, { "code": "battery_percentage", "custom_name": "", "dp_id": 4, "time": 1730129257001, "type": "value", "value": 100 }, { "code": "pir_sensitivity", "custom_name": "", "dp_id": 9, "time": 1730129237739, "type": "enum", "value": "high" }, { "code": "pir_time", "custom_name": "", "dp_id": 10, "time": 1730129237227, "type": "enum", "value": "10S" }, { "code": "illuminance_value", "custom_name": "", "dp_id": 12, "time": 1730130373101, "type": "value", "value": 2392 }, { "code": "interval_time", "custom_name": "", "dp_id": 102, "time": 1730129400748, "type": "value", "value": 1 } ] }

**Comment by bobvandevijver** [comment]
The `illuminance_value` isn't part of the standard status set, so it will not be implemented with a native Homey capability. You can however already achieve what you want using the provided data flow cards: just select that code and use the logic cards to process the incoming value further.

![image](https://github.com/user-attachments/assets/4d0a50ea-8459-413f-a4c5-cebfd17abf22)

**Comment by pinpoint90** [comment]
Thanks! :)
