### ISSUE TITLE
Climate Sensor

### ISSUE THREAD

**Issue by kfhakan** [athombv/com.tuya#294]
### Homey version

2023 Homey Pro

### Tuya app version

1.0.1

### Description

Hi
I run a Homey Pro with two Homey bridges with several different connected units. So far I have never failed to add a unit present in your register. This time I failed. After 6 hours and 110 tries I give up and write to you. I shall connect 4 Tuya WIFI Temp& Humidity units (presented “Climate” in your register). When I tried to “add” the normal way I got the message to connect the unit to Smart Life or Tuya app on my iPhone – no problem I ran two other units on the Smart Life app. It connected quickly and all data was properly presented on the iPhone. It was also in the app connected to Google Assistant …and worked also there properly….so back to my Homey connection again. Units, (+),New unit,- hit the Tuya symbol, and also the symbol “Climate sensor”. New field with a blue line “Connect”-new screen again with the two symbols and the txt “before you proceed…..”. pushed continue…new screen. Sweden came up (+46) and asked to write my cellphone number or email….( I tried them 50-60 times each). I also “x” the field I agree, and did the next step-verification “puzzle”. Accepted -verification ok!...but then hell was loose! New field said
“Hint”
The account password does not match. Please reenter the password or try to switch region. (there are two regions China and International course the choice was international. Doesn´t matter -I can do it 110 times more with the same result. (I even tried China ….)
The account on Smart Life works properly – the Tuya units work in the app properly, password is correct (doublechecked) but I can´t pass this point. Its connected to 2,4 , its connected correct (of course -its working and send correct data. Is it possible to get some help here before I drop down with a heart attack or crush the units to pices?

The account password does not match. Please reenter the password or try to switch region😬.
Is there any solution? I red this phrase 110 times today!

Almost crazy hello`s from Sweden
Hakan [haakan@ydner.se](mailto:haakan@ydner.se)

**Comment by bobvandevijver** [comment]
Your submitted app version is probably a typo, otherwise please make sure to updated to the latest.

However, there seems to be an authentication issue on the Tuya side (see #295), so that will probably be the reason of your issue. I am closing this to only keep a single ticket on the same issue.

**Comment by bobvandevijver** [comment]
Then why do you submit version 1.0.1 instead of the latest which is 1.4.1?

**Comment by kfhakan** [comment]
I was not aware of the the update index-in my version of Smart Life no version index is presented -it only says ”All updated” and this version was preprinted in the form. For my Homey the version is 12.1.2
I have six itemproducers and 60 units presnted and so far I have not met any problem. 
I thought we could help out to reach a solution- so pls tell me where the version number can be red.
I am not an expert on Homey or Tuya - just an ordinary customer trying to find some help to solve a problem

Kfhakan

**Comment by bobvandevijver** [comment]
It's about the version of the Tuya app on your Homey, so I am assuming that you just have the latest as it should be automatically updated unless disabled explictly.

You can follow the other ticket for updates regarding the login, something did indeed break for the initial login.
