### ISSUE TITLE
Request Device: I Smart Circuit Breaker

### ISSUE THREAD

**Issue by stianelverland** [athombv/com.tuya#30]
TUYA WIFI Smart Circuit Breaker With Metering 1P 63A DIN Rail for Smart Home  wireless Remote Control Switch by APP TONGOU
https://a.aliexpress.com/_mMvucz2

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.
