### ISSUE TITLE
Request Device: Garage Door Opener

### ISSUE THREAD

**Issue by stianelverland** [athombv/com.tuya#31]
Tuya Smart life Garage Door Opener Wifi Switch ewelink APP Control Audio Password Control Real Time Monitor Work With Alexa Siri
https://a.aliexpress.com/_ms2yfw0

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by bobvandevijver** [comment]
Closing this due to missing info. If still relevant, please open a new issue and provide the information as described in the templates.
