### ISSUE TITLE
Tuya curtain switch module (single and dual)

### ISSUE THREAD

**Issue by pwvandeursen** [athombv/com.tuya#32]
Not able to do CLI unfortunately. Here the link to the device:

https://nl.aliexpress.com/item/1005005225077998.html?spm=a2g0o.order_detail.order_detail_item.11.13186d76SsjhFg&gatewayAdapt=glo2nld

Here the link to the Tuya community app discussing all the inputs and settings of the device:

dual version: https://github.com/JohanBendz/com.tuya.zigbee/issues/362
single version: https://github.com/JohanBendz/com.tuya.zigbee/issues/361, 
https://github.com/JohanBendz/com.tuya.zigbee/pull/729,
https://github.com/JohanBendz/com.tuya.zigbee/issues/766, 
https://github.com/JohanBendz/com.tuya.zigbee/issues/808,

![image](https://github.com/athombv/com.tuya/assets/10534746/7560b369-ab70-4b8f-95fe-25653dcdd7cf)

**Comment by bobvandevijver** [comment]
You have added links to Zigbee devices: this means they need to be connected to a Tuya Zigbee hub to be able to be used with this cloud based app. This app won't support the Zigbee devices directly.
