### ISSUE TITLE
Login through mobile Chrome browser fails

### ISSUE THREAD

**Issue by PeterKawa** [athombv/com.tuya#33]
App v0.7.0

When adding the first device with mobile Homey app, login procedure fails; my phone opens Chrome browser by default:
![b205c7d747f990509d39be05c3037c254a598b2c_2_460x1000.jpeg](https://github.com/athombv/com.tuya/assets/74005072/65de6132-f5b5-4a09-a479-2174f762ed54)

But, when adding the first device with the web app @ Firefox, login works fine.

I can reproduce it by opening the URL below. 
Chrome  = ❌
Firefox = ✅
The full redirect URL I catched is:
https://openapi.tuyaus.com/login?state=b9eb826d-ca54-4ebe-abeb-e585187760ec&client_id=ypx5nej9gtpqrnqc8jca&response_type=code&scope=&redirect_uri=https%3A%2F%2Ftuya.athom.com%2Fcallback

**Comment by PeterKawa** [comment]
It's a Samsung S9 Android 10, Emile.
But it's no individual issue, see topic https://community.homey.app/t/neue-tuya-app/111982/3

Oauth: login to Spotify works. Do you need me to test with other logins?

**Comment by OldeWeghuis** [comment]
Same problem here, also an Android phone here.

**Comment by sasscz** [comment]
Same problem here, Android and Linux Ubuntu 22.04 Firefox - Chrome both tested in private mode, not possible for me to login

**Comment by bobvandevijver** [comment]
We believe this issue has been fixed by Tuya: if it does persist, please create a new ticket!
