### ISSUE TITLE
Log in / token issue

### ISSUE THREAD

**Issue by SofiaMagdalena999** [athombv/com.tuya#36]
Logged in to my Tuya app account through Homey and was then able to add two lights (logged in through add function) but then when I want to add more devices of a different kind I am told to log in again. 
At the end of log in process I am told I ant tlog in cause I am already logged in. 
This happened day before yesterday. 
Today when I want to use the devices I have added they state "Token missing."
And now when I try and add new device (the only way I know how to log in) I get "New device found - Token is expired (Code 1010)"

**Comment by PeterKawa** [comment]
Try using a private browser tab as workaround

**Comment by SofiaMagdalena999** [comment]
It works thank you. :)
