### ISSUE TITLE
Error during logging in.

### ISSUE THREAD

**Issue by sulisenator** [athombv/com.tuya#40]
I'm getting an error while trying to login.

![image](https://github.com/athombv/com.tuya/assets/7558319/e8f69f65-375a-4e4c-8e4d-1712e21d41a6)

**Comment by MerelHudepohl** [comment]
@sulisenator which region are you trying to login to?

**Comment by bobvandevijver** [comment]
Closing this due to its age. If you can still not authenticate try to reset your password first, and make sure to use https://my.homey.app with a laptop/desktop for the initial pairing process.
