### ISSUE TITLE
Tuya plug shows 10x more energy consumptin then in reality

### ISSUE THREAD

**Issue by wannes62** [athombv/com.tuya#42]
The tuya plug shows 10x more energy consumption in Homey pro than in the tuya app on my phone
<img width="414" alt="20240713_195012435_iOS" src="https://github.com/user-attachments/assets/37c536d6-0127-4365-ad4d-ff7cd26b3c55">
![Schermafbeelding 2024-07-13 213613](https://github.com/user-attachments/assets/b5234d6a-5a82-4438-b6fa-c9474d1949c8)

**Comment by m4xx75** [comment]
Hello, same issue here:
![Screenshot_20240719_015939_Homey](https://github.com/user-attachments/assets/f29aa564-0221-4c20-ab82-676bad3693ae)
![Screenshot_20240719_015933_Homey](https://github.com/user-attachments/assets/a1f001f7-5315-4730-8674-1ee4ce40dc5a)
![Screenshot_20240719_020352_Smart Life](https://github.com/user-attachments/assets/62a8e8da-6c56-4832-9108-097c3e891b6b)
Thank you !

**Comment by bobvandevijver** [comment]
Thank you for your reports, it seems that not all sockets behave equal with respect to how the power is reported. We have added a setting in version v1.0.1 (currently in test) so it can be adjusted per device!

**Comment by m4xx75** [comment]
It works perfectly, thank you!
