### ISSUE TITLE
Problems setting up a new Plug type device

### ISSUE THREAD

**Issue by chrispeterpdm** [athombv/com.tuya#43]
I cannot install new plugs as a device from SmartLife. I get an error message in both the app and the WEB app.
![Screenshot_20240716_132104_Homey](https://github.com/user-attachments/assets/17c03759-2dfe-4222-a9b6-b5f4738ac58c)
![Screenshot_20240716_132104_Homey](https://github.com/user-attachments/assets/b7930d56-35d0-465b-856e-0757ef4afac2)

**Comment by jampeef** [comment]
try adding it as other. will probably be added but have no working functions. So ju need to request device in issues

**Comment by bobvandevijver** [comment]
Closing this to clean up older tickets. If the issue persists with the latest version you can create a new ticket.
