### ISSUE TITLE
[Device Request]: CEILING_FAN_LIGHT: 'fsd' not supported by FAN Device

### ISSUE THREAD

**Issue by mruiter** [athombv/com.tuya#45]
Most used ceiling fan device on the Tuya platform is the 

CEILING_FAN_LIGHT: 'fsd'

This isnt supported yet in the current FAN device so it limits the FAN device usage of the app

These devices mostly have 3 speeds , low , medium, high and lights on and off

**Comment by gslender** [comment]
My fork does - if you're capable of installing it, do so and get the full use of the light and fan

https://github.com/gslender/com.tuya

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by mruiter** [comment]
`{
    "device": {
        "active_time": 1720967470,
        "biz_type": 18,
        "category": "fsd",
        "create_time": 1720967470,
        "icon": "smart/icon/ay1512497784834trnvi/15581809942e4c56820f3.jpg",
        "id": "bf83179e8e229e0411leps",
        "ip": "<redacted>",
        "lat": "<redacted>",
        "local_key": "<redacted>",
        "lon": "<redacted>",
        "model": "QI-FLRC-1",
        "name": "Ceiling fan light",
        "online": true,
        "owner_id": "<redacted>",
        "product_id": "fcldsaadc3hzf9ey",
        "product_name": "Ceiling fan light",
        "status": [
            {
                "code": "switch",
                "value": false
            },
            {
                "code": "fan_speed",
                "value": "2"
            },
            {
                "code": "countdown",
                "value": "0"
            },
            {
                "code": "countdown_left",
                "value": 0
            },
            {
                "code": "light",
                "value": false
            },
            {
                "code": "fan_beep",
                "value": true
            }
        ],
        "sub": false,
        "time_zone": "+02:00",
        "uid": "<redacted>",
        "update_time": 1723168849,
        "uuid": "<redacted>"
    },
    "specifications": {
        "category": "fsd",
        "functions": [
            {
                "code": "switch",
                "desc": "{}",
                "name": "开关",
                "type": "Boolean",
                "values": "{}"
            },
            {
                "code": "fan_speed",
                "desc": "{\"range\":[\"1\",\"2\",\"3\"]}",
                "name": "风速",
                "type": "Enum",
                "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
            },
            {
                "code": "countdown",
                "desc": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\"]}",
                "name": "倒计时",
                "type": "Enum",
                "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\"]}"
            },
            {
                "code": "light",
                "desc": "{}",
                "name": "灯光开关",
                "type": "Boolean",
                "values": "{}"
            },
            {
                "code": "fan_beep",
                "desc": "{}",
                "name": "声音",
                "type": "Boolean",
                "values": "{}"
            }
        ],
        "status": [
            {
                "code": "switch",
                "name": "开关",
                "type": "Boolean",
                "values": "{}"
            },
            {
                "code": "fan_speed",
                "name": "风速",
                "type": "Enum",
                "values": "{\"range\":[\"1\",\"2\",\"3\"]}"
            },
            {
                "code": "countdown",
                "name": "倒计时",
                "type": "Enum",
                "values": "{\"range\":[\"0\",\"1\",\"2\",\"3\",\"4\",\"5\",\"6\",\"7\",\"8\",\"9\",\"10\",\"11\",\"12\",\"13\",\"14\",\"15\",\"16\"]}"
            },
            {
                "code": "countdown_left",
                "name": "倒计时剩余时间",
                "type": "Integer",
                "values": "{\"unit\":\"min\",\"min\":0,\"max\":960,\"scale\":0,\"step\":1}"
            },
            {
                "code": "light",
                "name": "灯光开关",
                "type": "Boolean",
                "values": "{}"
            },
            {
                "code": "fan_beep",
                "name": "声音",
                "type": "Boolean",
                "values": "{}"
            }
        ]
    }
}`

**Comment by bobvandevijver** [comment]
Version 1.3.0 should support this device!
