### ISSUE TITLE
[Device Request]: Tuya wifi temp humidity sensor

### ISSUE THREAD

**Issue by jampeef** [athombv/com.tuya#48]
there are a handfull of these, different manufacturers, same device. 
https://www.amazon.se/-/en/Temperature-Hygrometer-Thermometer-Compatible-Intelligent/dp/B0BMLMQ3RM

2024-07-18T07:40:50.395Z [log] [ManagerDrivers] [Driver:other] Device: {"active_time":1719820039,"biz_type":0,"category":"wsdcg","create_time":1719820039,"icon":"smart/icon/bay1624869296421wDFy/6598557dfaa15cd5c2dcaa3699413fb1.png","id":"","ip":"","lat":"63.8798","local_key":"","lon":"20.3111","model":"","name":"WIFI-TH-2023 2","online":true,"owner_id":"","product_id":"","product_name":"WIFI-TH-2023","status":[{"code":"va_temperature","value":62},{"code":"va_humidity","value":61},{"code":"battery_percentage","value":14},{"code":"temper_alarm","value":false},{"code":"maxtemp_set","value":600},{"code":"minitemp_set","value":-100},{"code":"maxhum_set","value":100},{"code":"minihum_set","value":0},{"code":"temp_alarm","value":"cancel"},{"code":"hum_alarm","value":"cancel"}],"sub":false,"time_zone":"+02:00","uid":"","update_time":1721286816,"uuid":""}

**Comment by bobvandevijver** [comment]
We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by jampeef** [comment]
Oh sorry might have redacted a little too much on the previous post :)

{ "device": { "active_time": 1719776337, "biz_type": 0, "category": "wsdcg", "create_time": 1719776337, "icon": "smart/icon/bay1624869296421wDFy/6598557dfaa15cd5c2dcaa3699413fb1.png", "id": "bf134dd00505862a7adhy6", "ip": "<redacted>", "lat": "<redacted>", "local_key": "<redacted>", "lon": "<redacted>", "model": "", "name": "WIFI-TH-2023", "online": true, "owner_id": "<redacted>", "product_id": "vadjntdjedbnne0h", "product_name": "WIFI-TH-2023", "status": [ { "code": "va_temperature", "value": 255 }, { "code": "va_humidity", "value": 60 }, { "code": "battery_percentage", "value": 26 }, { "code": "temper_alarm", "value": false }, { "code": "maxtemp_set", "value": 600 }, { "code": "minitemp_set", "value": -100 }, { "code": "maxhum_set", "value": 100 }, { "code": "minihum_set", "value": 0 }, { "code": "temp_alarm", "value": "cancel" }, { "code": "hum_alarm", "value": "cancel" } ], "sub": false, "time_zone": "+02:00", "uid": "<redacted>", "update_time": 1723042102, "uuid": "<redacted>" }, "specifications": { "category": "wsdcg", "functions": [ { "code": "maxtemp_set", "desc": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}", "name": "温度上限设置", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}" }, { "code": "minitemp_set", "desc": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}", "name": "温度下限设置", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}" }, { "code": "maxhum_set", "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "name": "湿度上限设置", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "minihum_set", "desc": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}", "name": "湿度下限设置", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" } ], "status": [ { "code": "va_temperature", "name": "当前温度", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}" }, { "code": "va_humidity", "name": "湿度数值", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "battery_percentage", "name": "电池电量", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "temper_alarm", "name": "防拆报警", "type": "Boolean", "values": "{}" }, { "code": "maxtemp_set", "name": "温度上限设置", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}" }, { "code": "minitemp_set", "name": "温度下限设置", "type": "Integer", "values": "{\"unit\":\"℃\",\"min\":-200,\"max\":600,\"scale\":1,\"step\":1}" }, { "code": "maxhum_set", "name": "湿度上限设置", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "minihum_set", "name": "湿度下限设置", "type": "Integer", "values": "{\"unit\":\"%\",\"min\":0,\"max\":100,\"scale\":0,\"step\":1}" }, { "code": "temp_alarm", "name": "温度报警", "type": "Enum", "values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}" }, { "code": "hum_alarm", "name": "湿度报警", "type": "Enum", "values": "{\"range\":[\"loweralarm\",\"upperalarm\",\"cancel\"]}" } ] } }

**Comment by bobvandevijver** [comment]
You didn't redact too much, we changed the implementation to share more relevant information. Thank you!
