### ISSUE TITLE
LSC PIR Motion alarm never turns off

### ISSUE THREAD

**Issue by PeterKawa** [athombv/com.tuya#5]
When LSC PIR is added as new Homey device, the motion alarm is on right away. 
Nothing changes when motion is detected. 
(Note: exact same behaviour as in Home Assistant
[Tuya integration](https://github.com/home-assistant/core/issues/58634); it records motion events however, but never gets cleared)

Temp fix: add virtual sockets with a iot.tuya.com developer account, [go to this site](https://developer.tuya.com/en/docs/iot/manage-virtual-devices?id=Ka4725tiyfhg0), 
with Tuya phone app, have the PIR switch the socket on/off, now you can use that socket as 'sensor' in HA / Homey.

![Screenshot_20240605-231427_Homey.jpg](https://github.com/athombv/com.tuya/assets/74005072/b5b8ce8b-c25e-42ba-befb-854fbd22f738)

![Screenshot_20240605-231444_Homey.jpg](https://github.com/athombv/com.tuya/assets/74005072/aa46bf80-5185-4309-a1ad-1e98e32409a5)

The mobile TuyaSmart app registers motion correctly
![Screenshot_20240605-232326_Tuya Smart.jpg](https://github.com/athombv/com.tuya/assets/74005072/608f39d5-4265-423f-b320-10db1ef20462)

**Comment by WeeJeWel** [comment]
Thanks for reporting! I have created a new issue #7 to combine these issues in one place to track the progress.
