### ISSUE TITLE
Cant connect with oauth

### ISSUE THREAD

**Issue by ricardovanlaarhoven** [athombv/com.tuya#54]
When trying to connect via the android app, nothing happens after you see the honey message to close the browser, just after tuya redirects you there.

When i do the same thing, via the webapp, i'm getting the message oauth client already exists.

I already checked my app and see under account and security -> cloud development project -> homey

When removing that and trying it again, the same thing happens.

**Comment by crazzyyfool** [comment]
I have the same issue.

**Comment by bobvandevijver** [comment]
Please make sure to restart the Tuya app or your Homey and then try again using https://my.homey.app. If you get the same message and you do not have too many Tuya devices linked with Homey yet, you can try to reinstall the app.

**Comment by ks2018ks** [comment]
I have the same problem: 
Tuya App version 1.1.0
Homey app version 8.3.0.1518
Homey pro 2023 12.0.0

Select devices > new device > Tuya > Other > Connect > Conitnue > Login > enter Tuya Smart email > agree to terms of service > Next step > Slide jigsaw puzzle > Tuya Smart > Next step  > enter password > agree to terms of service > log in > Slide jigsaw puzzle > Confirm authorization > "You can now close this window" > Close window and Homey app shows "Login with your account" + one of the following:

1. Spinning icon with 'Please login on the website of the manufacturer '
2. Blank
3. OAuth already <disappears too fast to read the full message

Tried:
Restarting Tuya app
Restarting Homey app
Rebooting Homey, 
Rebooting Phone

None of the above makes any difference

**Comment by bobvandevijver** [comment]
@ks2018ks Did you try to authenticate using a browser on a laptop/desktop using https://my.homey.app? If not, please try that first.

**Comment by ricardovanlaarhoven** [comment]
> @ks2018ks Did you try to authenticate using a browser on a laptop/desktop using https://my.homey.app? If not, please try that first.


On browser using a desktop, the popup disapears so fast, no error is visible.
But it doesnt work either.

**Comment by Bossie53** [comment]
The Smart Life app does indicate that it is connected to Homey.

But cannot add devices from Tuya in Homey.

You must then give access to the Smart life app again and again.

**Comment by Bossie53** [comment]
Works now.
 Remove app tuya from homey.
 Restart Homey.
 Install tuya app again and follow installation steps again.
 Then it worked.

**Comment by jorgenhs** [comment]
Had same error "OAuth2 client already exists", followed steps above:
Uninstall Tuya app
Restart Homey
Reinstall Tuya app.
OAuth completes successfully.

However, now having problem where app says briefly "discovered new devices", then "could not install devices. Took too much time" (paraphrased from Norwegian error message)

Will pursue that new problem in a separate issue.

**Comment by ricardovanlaarhoven** [comment]
The same actions i did before, do now work :)
