### ISSUE TITLE
Staniot Security Panel 3

### ISSUE THREAD

**Issue by RonMone** [athombv/com.tuya#58]
<details>

```json
{
  "active_time": 1654271064,
  "biz_type": 18,
  "category": "mal",
  "create_time": 1654271064,
  "icon": "smart/icon/ay1569410984379VeGPj/f0b83cf87ff25cca63b16c86a12aa44b.png",
  "id": "bf648ba2f34fd1e519h3j7",
  "ip": "86.93.121.228",
  "lat": "52.51",
  "local_key": "cf1084d8d34e813e",
  "lon": "5.07",
  "model": "",
  "name": "Beveiliging",
  "online": true,
  "owner_id": "25513371",
  "product_id": "d7dgjao5nvj03p5q",
  "product_name": "Smart Security Panel",
  "status": [
    {
      "code": "master_mode",
      "value": "disarmed"
    },
    {
      "code": "delay_set",
      "value": 0
    },
    {
      "code": "alarm_time",
      "value": 3
    },
    {
      "code": "switch_alarm_sound",
      "value": true
    },
    {
      "code": "switch_alarm_light",
      "value": true
    },
    {
      "code": "switch_mode_sound",
      "value": false
    },
    {
      "code": "switch_mode_light",
      "value": false
    },
    {
      "code": "switch_kb_light",
      "value": true
    },
    {
      "code": "charge_state",
      "value": true
    },
    {
      "code": "battery_percentage",
      "value": 100
    },
    {
      "code": "switch_low_battery",
      "value": false
    },
    {
      "code": "alarm_call_number",
      "value": "AQUCAQEMKzMxNjU0OTc0MjA0AgwrMzE2MjI1MDc1OTU="
    },
    {
      "code": "switch_alarm_call",
      "value": false
    },
    {
      "code": "switch_alarm_sms",
      "value": false
    },
    {
      "code": "telnet_state",
      "value": "phone_no"
    },
    {
      "code": "muffling",
      "value": false
    },
    {
      "code": "alarm_msg",
      "value": "AEkAbgBnAGEAbgBnACAAZwBlAG8AcABlAG4AZAAgAFYAYQBuADoAVgBvAG8AcgBkAGUAdQBy"
    },
    {
      "code": "switch_alarm_propel",
      "value": true
    },
    {
      "code": "alarm_delay_time",
      "value": 0
    },
    {
      "code": "switch_mode_dl_sound",
      "value": true
    },
    {
      "code": "master_state",
      "value": "normal"
    },
    {
      "code": "master_information",
      "value": ""
    },
    {
      "code": "sub_type",
      "value": "motion_sensor"
    },
    {
      "code": "sub_admin",
      "value": "AQAD"
    },
    {
      "code": "master_language",
      "value": "netherlands"
    }
  ],
  "sub": false,
  "time_zone": "+02:00",
  "uid": "eu1612681271073EzPz5",
  "update_time": 1720867647,
  "uuid": "155b482433ab57a9"
}
```
</details>

https://www.staniot.com/productinfo/99336.html
https://www.aliexpress.com/item/1005006859756872.html?spm=a2g0o.productlist.main.7.65a61b1ewnYdo1&algo_pvid=4434cba3-4de5-4b27-aac2-e9f4979287d6&algo_exp_id=4434cba3-4de5-4b27-aac2-e9f4979287d6-3&pdp_npi=4%40dis%21EUR%21295.73%21138.99%21%21%212288.97%211075.82%21%40211b600e17211473081737834ee36d%2112000038611897641%21sea%21NL%21832316559%21&curPageLogUid=dKSmAUYGE4PR&utparam-url=scene%3Asearch%7Cquery_from%3A

**Comment by bobvandevijver** [comment]
@RonMone We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The [new issue](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+) template provides a short how to.

**Comment by RonMone** [comment]
Bob,

 

I uploaded the information on issue number #140

 

With regards,

Ron Moné

 

Van: Bob van de Vijver ***@***.***> 
Verzonden: woensdag 7 augustus 2024 16:28
Aan: athombv/com.tuya ***@***.***>
CC: RonMone ***@***.***>; Mention ***@***.***>
Onderwerp: Re: [athombv/com.tuya] Staniot Security Panel 3 (Issue #58)

 

@RonMone <https://github.com/RonMone>  We're missing some information, which can be retrieved from the advanced settings with the latest app version: you might need to re-add the device to be able to see the information. Can you please see if you can retrieve those details? The new issue <https://github.com/athombv/com.tuya/issues/new?assignees=&labels=device+request&projects=&template=device-request.yml&title=%5BDevice+request%5D%3A+>  template provides a short how to.

**Comment by bobvandevijver** [comment]
Closing this as duplicate of #140.
