### ISSUE TITLE
Request Device: moes tuya 

### ISSUE THREAD

**Issue by johnokerry** [athombv/com.tuya#61]
hi there 

new to this so sorry if this is the wrong place. i added the new tuya app and when i bring them in i can't control them i have tried bring them in as a light but it will not find them. below is attached photo of what i am seen. devices are below. smartlife is the app i use.

MoesGo 1 Gang DIY Zigbee Smart Light LED Dimmer Switch Module, Tuya Zigbee Hub Required, Smart Life&Tuya App 
link  here https://www.amazon.co.uk/dp/B08622JN22?psc=1&ref=ppx_yo2ov_dt_b_product_details

i also have 3 wifi dimmers MOES WiFi Smart Touch Light Dimmer Switch link https://www.amazon.co.uk/dp/B08XM5P6D1?psc=1&ref=ppx_yo2ov_dt_b_product_details

![1111](https://github.com/user-attachments/assets/b3d435e5-16d3-485a-b641-d0394d3d99df)
![11](https://github.com/user-attachments/assets/11bd4d7d-068f-4574-bae2-70929a44fd76)

**Comment by bobvandevijver** [comment]
Thank you for your request. We are already working on dimmer support (#46), which should become available soon!

**Comment by johnokerry** [comment]
> Thank you for your request. We are already working on dimmer support (#46), which should become available soon!

thanks it would be great as all my stuff is tyua platform.
