### ISSUE TITLE
Logging in v. 1.0

### ISSUE THREAD

**Issue by xdwarf** [athombv/com.tuya#62]
Hi. 

When i try to add a new device it redirects me to a tuya login page where the only option i have is to enter my phone number, and when i do so it tells me my password is incorrect.
The i can re-enter or switch region, but it just resets the page and i can enter my phone number again. What to do?

Kind regards
Mads
![HomeyTuya](https://github.com/user-attachments/assets/a395c923-72c0-4b04-8898-a4265b173224)

**Comment by Domingoso** [comment]
Instead of phone number, just write there your email address. It works for me.

**Comment by bobvandevijver** [comment]
You can also try to change the region in your top left to match your region.

**Comment by xdwarf** [comment]
Man do i feel stupid right now. I hadnt read that i could choose to type in my email. I was so focused on the area code that i felt like i couldnt put in anything else than a phone number.
I used my email and now everything works like a charm.

Thanks again.

**Comment by bobvandevijver** [comment]
Great to hear your issue has been resolved!
