### ISSUE TITLE
Login not possible

### ISSUE THREAD

**Issue by robertomario76** [athombv/com.tuya#63]
every time I try to connect a device the login request is activated. I execute the login procedure, at the end the login window closes and the message "OAuth2 Client already exists" appears and nothing else happens.

**Comment by bobvandevijver** [comment]
Did you try to restart the app/your Homey? It can help clear this state. If you do not have too many Tuya devices yet an app reinstall can also solve this issue.

**Comment by robertomario76** [comment]
good morning, I tried restarting both the app and homey. I also uninstalled and reinstalled the app.
I haven't connected any devices yet.
currently I use tuya cloud which is the app created by the community, but this uses the tuya developer account and not the smart life or tuya user account

**Comment by bobvandevijver** [comment]
Great to hear your issue has been resolved!
