### ISSUE TITLE
Nedis plug works but I cannot switch off/on

### ISSUE THREAD

**Issue by DanKaihoj** [athombv/com.tuya#73]
My nedis plug is available in tuya smart and homey. I can Even see the ENERGY consumption in homey, great.

But I can not presse it in homey to switch it off, and via a flow i do not see an action card to switch on / off. Where do I go wrong?

Best regards

Dan

**Comment by bobvandevijver** [comment]
Please use the [issue template](https://github.com/athombv/com.tuya/issues/new?assignees=&labels=bug&projects=&template=bug-report.yml) and supply the requested information. Without that information there isn't much we can do.

**Comment by PeterKawa** [comment]
@DanKaihoj 
You can use the general plug flow card for now
![Screenshot_20240727-045848_Chrome.jpg](https://github.com/user-attachments/assets/8d5b927c-11c7-4fa2-b09e-58660ca75ff2)

On/Off is a boolean action ( = 1/0 - true/false - on/off)
When you click into the [code] field, a list of possible device functions appear, like "switch_1".

**Comment by DanKaihoj** [comment]
Thanks i i will do that. In local homey groups people are asking the same questions like i do. Does there exist a visual guide how to get the sats that is needed to make the devices supported?

If so i can share it and promote it in the groups i know of.

Best regards

Dan

Sendt fra Outlook til Android<https://aka.ms/AAb9ysg>
________________________________
