### ISSUE TITLE
[Device request]: “Mini Wi-Fi Remote Control Smart Socket with Practical Timing, Adjustable RGB LED Color, Intelligent Plug with LED Indicator, and Power Measurement Capabilities.”

### ISSUE THREAD

**Issue by HPLvanM** [athombv/com.tuya#74]
### Device information

![Negaor-01 jpg-05](https://github.com/user-attachments/assets/f9d1f220-b964-4c93-b874-0468d671a059)

### Device specification

Device Specification
<details>
{ "device": { "active_time": 1595450710, "biz_type": 18, "category": "dj", "create_time": 1565114579, "icon": "smart/icon/15236002431ht4plmhhyrzxxim6smtl6jemi_0.jpg", "id": "84521276ecfabca43a45", "ip": "<redacted>", "lat": "<redacted>", "local_key": "83ffe723fe82c002", "lon": "<redacted>", "model": "HYS-01-077", "name": "1 - Raamlamp", "online": true, "owner_id": "5338519", "product_id": "DEQevYCSHLnbDube", "product_name": "RGB Smart Plug", "status": [ { "code": "switch_led", "value": false }, { "code": "work_mode", "value": "colour" }, { "code": "bright_value", "value": 255 }, { "code": "colour_data", "value": "{\"h\":323.0,\"s\":204.0,\"v\":255.0}" }, { "code": "scene_data", "value": "{\"h\":226.0,\"s\":175.7,\"v\":180.0}" }, { "code": "flash_scene_1", "value": "{\"bright\":255,\"frequency\":50,\"hsv\":[{\"h\":120.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}" }, { "code": "flash_scene_2", "value": "{\"bright\":255,\"frequency\":50,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}" }, { "code": "flash_scene_3", "value": "{\"bright\":255,\"frequency\":50,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}" }, { "code": "flash_scene_4", "value": "{\"bright\":255,\"frequency\":50,\"hsv\":[{\"h\":0.0,\"s\":255.0,\"v\":255.0},{\"h\":120.0,\"s\":255.0,\"v\":255.0},{\"h\":60.0,\"s\":255.0,\"v\":255.0},{\"h\":300.0,\"s\":255.0,\"v\":255.0},{\"h\":240.0,\"s\":255.0,\"v\":255.0}],\"temperature\":255}" }, { "code": "switch", "value": false }, { "code": "countdown_1", "value": 0 }, { "code": "cur_current", "value": 146 }, { "code": "cur_power", "value": 247 }, { "code": "cur_voltage", "value": 2427 } ], "sub": false, "time_zone": "+01:00", "uid": "eu1565114132860Yt4b6", "update_time": 1721707069, "uuid": "84521276ecfabca43a45" }, "specifications": { "category": "dj", "functions": [ { "code": "switch_led", "desc": "{}", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "bright_value", "desc": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}", "name": "亮度", "type": "Integer", "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}" }, { "code": "work_mode", "desc": "{\"range\":[\"white\",\"colour\",\"scene\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"]}", "name": "工作模式", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"]}" }, { "code": "colour_data", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "彩光模式数", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "scene_data", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "情景模式数", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_1", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "柔光模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_2", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "缤纷模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_3", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "炫彩模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_4", "desc": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}", "name": "斑斓模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "switch", "desc": "{}", "name": "插座开关", "type": "Boolean", "values": "{}" }, { "code": "countdown_1", "desc": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}", "name": "倒计时1", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ], "status": [ { "code": "switch_led", "name": "开关", "type": "Boolean", "values": "{}" }, { "code": "work_mode", "name": "工作模式", "type": "Enum", "values": "{\"range\":[\"white\",\"colour\",\"scene\",\"scene_1\",\"scene_2\",\"scene_3\",\"scene_4\"]}" }, { "code": "bright_value", "name": "亮度", "type": "Integer", "values": "{\"min\":25,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}" }, { "code": "colour_data", "name": "彩光模式数", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "scene_data", "name": "情景模式数", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_1", "name": "柔光模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_2", "name": "缤纷模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_3", "name": "炫彩模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "flash_scene_4", "name": "斑斓模式", "type": "Json", "values": "{\"h\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":360,\"step\":1},\"s\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1},\"v\":{\"min\":1,\"scale\":0,\"unit\":\"\",\"max\":255,\"step\":1}}" }, { "code": "switch", "name": "插座开关", "type": "Boolean", "values": "{}" }, { "code": "cur_current", "name": "当前电流", "type": "Integer", "values": "{\"unit\":\"mA\",\"min\":0,\"max\":30000,\"scale\":0,\"step\":1}" }, { "code": "cur_power", "name": "当前功率", "type": "Integer", "values": "{\"unit\":\"W\",\"min\":0,\"max\":50000,\"scale\":0,\"step\":1}" }, { "code": "cur_voltage", "name": "当前电压", "type": "Integer", "values": "{\"unit\":\"V\",\"min\":0,\"max\":2500,\"scale\":0,\"step\":1}" }, { "code": "countdown_1", "name": "倒计时1", "type": "Integer", "values": "{\"unit\":\"s\",\"min\":0,\"max\":86400,\"scale\":0,\"step\":1}" } ] } }
</details>

**Comment by PeterKawa** [comment]
What can a developer do with a *picture*.... pls add a *link* to the product specifications ,thx.

**Comment by HPLvanM** [comment]
https://www.blokker.nl/caliber-slimme-stekker-met-led-rgb-verlichting-en-energiemeter---smart-plug---energiebesparing---wit-%28hwp101le%29/2378912.html

https://dewarmemat.nl/products/smart-plug-wifi-stopcontact-schakelaar

https://www.bol.com/nl/nl/p/moes-tuya-wifi-smart-plug-led-slimme-tussenstekker-tuya-actoren-16a/9300000110910576/

https://www.bol.com/nl/nl/p/slimme-stekker-set-van-2-smart-plug-16a-google-assistant-amazon-alexa-ifttt-en-tuya-met-stroommeting-en-led/9200000121660571/

and much more

**Comment by bobvandevijver** [comment]
Looks like your device identifies as a light, but also has `switch` and `switch_led` capabilities. You should be able to already control those capabilities using the custom code/value boolean card, so you can try that if you want.

**Comment by HPLvanM** [comment]
yes it is possible to use advanced flows to "Set switch to boolean true" :-)
