### ISSUE TITLE
Please instruct people to remove sensitive JSON data (ip, gps (lat,lon) ) from the device json response

### ISSUE THREAD

**Issue by eelco2k** [athombv/com.tuya#80]
### Homey version

Homey Pro 2023

### Tuya app version

latest

### Description

I see a lot of users just dumping their "unknown device" JSON data in github issues.  without removing sensitive information like: "ip", "lat", "lon" (gps location). Perhaps this is a good idea to instruct users to remove those fields from the json before posting it online

### Device specification

```json
  { "device": "lat":"11.1111", "lon": "1.111" , "ip": "10.0.0.1" }
```

**Comment by eelco2k** [comment]
or at least filter the response in when running the app as this information is absolutely irrelevant for requesting device support for a specific tuya device.

**Comment by bobvandevijver** [comment]
Thank you for notifying us about this issue. Are you up for a PR? I do like to not remove the fields, but only redact their value with something recognisable such as `<redacted>` so we can recognise what our parsing has done.

**Comment by eelco2k** [comment]
as requested and a good choice to "redact" the field, here the PR: https://github.com/athombv/com.tuya/pull/92
