### ISSUE TITLE
[Device request]: Tuya Smart Sprinkler (8 stations)

### ISSUE THREAD

**Issue by Rrrr4321** [athombv/com.tuya#83]
### Device information

1. https://www.aliexpress.com/item/1005006170256463.html?spm=a2g0o.cart.0.0.1ab138daE5hErA&mp=1
2. It works through Homey Pro + Tuya Cloud app but required "catching" boolean events and DeviceIDs
3. I can install the sprinkler through the official Tuya app as OTHER device but not control the sprinkler
4. Lmk if you need more info

### Device specification

<details>

```json
{
  "device": {
    "active_time": 1714561192,
    "biz_type": 0,
    "category": "sfkzq",
    "create_time": 1714561192,
    "icon": "smart/icon/ay1513061730920i97zP/b839fe5cf4535c3d7410f86eb58f02da.jpg",
    "id": "bff0c957a5d016aaddiuha",
    "ip": "85.130.139.77",
    "lat": "32.1728",
    "local_key": "Am*eci?&zL{@tBoN",
    "lon": "34.8136",
    "model": "SH07X_GM",
    "name": "Smart Sprinkler Controller",
    "online": true,
    "owner_id": "43183280",
    "product_id": "krvsermlavj3lypv",
    "product_name": "Smart Sprinkler Controller",
    "sub": false,
    "time_zone": "+03:00",
    "uid": "eu1638089168442OcmmB",
    "update_time": 1722083528,
    "uuid": "7c303e72f1b42751"
  },
  "specifications": {
    "category": "sfkzq"
  }
}
```

</details>

**Comment by bobvandevijver** [comment]
Thank you for your request. Unfortunately, based on the specification you've submitted it seems to be an undocumented device which does not expose any properties we can access, which makes it impossible to support with Homey.
