### ISSUE TITLE
Hint/idea/request: Enabling tap-to-run scenes and or RAW Commands functionality

### ISSUE THREAD

**Issue by PeterKawa** [athombv/com.tuya#9]
A hint / idea / request:  
To overcome the fact a device type isn’t supported (yet), Tuya has the possibility to start (with TuyaSmart / SmartLife mobile app created) tap-to-run scenes from the cloud, and it has RAW commands functionality, Tuya’s version of MQTT so to speak. 
Although I'm not shure it is enabled and available with the current API?
It's enabled and functioning well with the Tuya Cloud app by Jurgen Heine.

When this functionality would be added to your Tuya app, almost any Tuya device can be controlled by Homey, and any Homey device can be controlled by Tuya, by using flows (the latter with RAW commands only).

Users can f.e. add a virtual device in order to create a ‘real’ device, to be able to control it / read its sensor values.

Thanks,
/Peet

**Comment by WeeJeWel** [comment]
Can you give an example of such a command?

**Comment by WeeJeWel** [comment]
<img width="407" alt="Screenshot 2024-06-07 at 10 39 48" src="https://github.com/athombv/com.tuya/assets/319873/db698630-9a96-4167-beff-c95bd34da2f0">

Something like this? 😏 

Added in the next version (v0.3.0).

**Comment by PeterKawa** [comment]
Yes! Sorry, didn't see your update very quickly.
