### ISSUE TITLE
No manual controls for Deltaco plug

### ISSUE THREAD

**Issue by mikkebu** [athombv/com.tuya#93]
### Homey version

Homey Pro 2023 12.0.0

### Tuya app version

1.1.0

### App diagnostics report ID

082bf7d6-1161-481c-bb0a-aa2ee372e183

### Description

No manual controls or on/off-cards for Deltaco plug
https://www.netonnet.se/art/hem-fritid/smarta-hem/smarta-uttag/deltaco-smart-plug-white-3-pack/1015357.19000/

https://aurdel.com/se/sv/sh-p01

![image](https://github.com/user-attachments/assets/66094dcb-9e94-459d-b240-1849f80055fb)
![image](https://github.com/user-attachments/assets/a5056df7-dc1d-4888-8e56-84e458ba97a5)

### Device specification

<details>

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
This switch also uses `switch` for the capability, instead of `switch_1`. Same as #79, but other brand.

**Comment by bobvandevijver** [comment]
Your issue should be fixed when we release 1.2.0: note that you will need to re-add your socket at that time.

**Comment by mikkebu** [comment]
Works great with release 1.2.0 (test)
