### ISSUE TITLE
Connecting Tuya with Homey

### ISSUE THREAD

**Issue by JWvanSetten** [athombv/com.tuya#98]
### Homey version

Homey Pro 2019-2023

### Tuya app version

v.1.1.0

### App diagnostics report ID

1fc7bb68-e69a-450b-8b45-lac71cd7a48f

### Description

Installing/Connecting the Official Tuya App: I received an email from Athom/LG on 18/07/2024 in a Homey "Newsletter" on how to connect my Tuya gateway to Homey with the text "Homey now officially supports Tuya!" I followed the procedure carefully with the correct apps and at the last step I get the attached images on my phone. The devices installed in the Tuya app are not visible in Homey. What could have gone wrong? I tried the procedure several times. Please any help
![Screenshot_20240730-154936](https://github.com/user-attachments/assets/09b0dc28-31e0-46ee-8e5f-d575bf9c77de)
![Screenshot_20240730-161719](https://github.com/user-attachments/assets/93cce97a-18f8-4991-9fd6-0365cfd9734a)

### Device specification

<details Sorry, when adding my device as "Other" I get the same screens as the files in the attachments.  >

```json
  { "device": ..., "specifications": ...}
```

</details>

**Comment by bobvandevijver** [comment]
Can you please try again using https://my.homey.app using a laptop/desktop?

**Comment by bobvandevijver** [comment]
Great to hear it works!

**Comment by JWvanSetten** [comment]
Beste Bob, het werkt nu, zoals verwachtte dat het zou werken !. Dankjewel voor de vlotte respons. Best regards, Jan
